export interface QuizQuestion {
  id: number;
  chapter: string;
  topic: string;
  question: string;
  options: [string, string, string];
  answerIndex: number;
  explanation: string;
}

export const quizQuestions: QuizQuestion[] = [
  {
    id: 1,
    chapter: "Chapter 1",
    topic: "Entropy",
    question: "If a room gets messier over time, which idea is it hinting at?",
    options: ["Entropy tends to increase", "Gravity turns off", "Energy disappears"],
    answerIndex: 0,
    explanation: "Entropy is a way to describe how many messy, spread-out arrangements are available.",
  },
  {
    id: 2,
    chapter: "Chapter 2",
    topic: "Blockchain",
    question: "What does a blockchain transaction signature prove?",
    options: ["The receiver is online", "The sender approved it", "The coin has weight"],
    answerIndex: 1,
    explanation: "A valid signature proves the transaction was authorized by the holder of the private key.",
  },
  {
    id: 3,
    chapter: "Chapter 3",
    topic: "AI",
    question: "What is the main job of training an AI model?",
    options: ["Memorize every website", "Turn code into electricity", "Adjust patterns from examples"],
    answerIndex: 2,
    explanation: "Training updates model parameters so it captures useful patterns in examples.",
  },
  {
    id: 4,
    chapter: "Chapter 4",
    topic: "Physics",
    question: "When you push a wall and it pushes back, which law are you seeing?",
    options: ["Pythagoras' theorem", "Newton's third law", "Moore's law"],
    answerIndex: 1,
    explanation: "Newton's third law says forces come in equal and opposite pairs.",
  },
  {
    id: 5,
    chapter: "Chapter 5",
    topic: "Proofs",
    question: "What makes a mathematical proof convincing?",
    options: ["Each step follows logically", "It uses big words", "It is written in red ink"],
    answerIndex: 0,
    explanation: "A proof works when every step follows from accepted assumptions or previous steps.",
  },
  {
    id: 6,
    chapter: "Chapter 6",
    topic: "Memory",
    question: "Which habit usually helps memory most?",
    options: ["Rereading once quickly", "Changing font color", "Testing yourself later"],
    answerIndex: 2,
    explanation: "Retrieval practice strengthens memory because you reconstruct the idea yourself.",
  },
  {
    id: 7,
    chapter: "Chapter 7",
    topic: "Markets",
    question: "If demand rises while supply stays the same, price usually does what?",
    options: ["Goes up", "Always goes to zero", "Becomes illegal"],
    answerIndex: 0,
    explanation: "More buyers competing for the same supply usually pushes price upward.",
  },
  {
    id: 8,
    chapter: "Chapter 8",
    topic: "Code",
    question: "What does a loop help a program do?",
    options: ["Repeat steps", "Hide the keyboard", "Make pixels heavier"],
    answerIndex: 0,
    explanation: "A loop repeats instructions until a condition stops it or the sequence ends.",
  },
  {
    id: 9,
    chapter: "Chapter 9",
    topic: "Probability",
    question: "A fair coin lands heads five times. What is the next flip most likely to be?",
    options: ["Definitely tails", "Still 50/50", "Definitely heads"],
    answerIndex: 1,
    explanation: "Past flips do not change the next flip of a fair coin; it remains 50/50.",
  },
  {
    id: 10,
    chapter: "Chapter 10",
    topic: "Learning",
    question: "What is an aha moment usually a sign of?",
    options: ["A mental model clicked", "You are done forever", "The question was fake"],
    answerIndex: 0,
    explanation: "An aha moment means pieces reorganized into a model you can carry forward.",
  },
  {
    id: 11,
    chapter: "Chapter 11",
    topic: "Algebra",
    question: "If x + 3 = 7, what is x?",
    options: ["4", "10", "21"],
    answerIndex: 0,
    explanation: "Subtract 3 from both sides and x = 4.",
  },
  {
    id: 12,
    chapter: "Chapter 12",
    topic: "Biology",
    question: "Which molecule carries genetic instructions in most living things?",
    options: ["Salt", "DNA", "Cholesterol"],
    answerIndex: 1,
    explanation: "DNA stores genetic instructions used by cells to build and regulate living systems.",
  },
  {
    id: 13,
    chapter: "Chapter 13",
    topic: "Philosophy",
    question: "Socrates is famous for asking questions mainly to expose what?",
    options: ["Weather patterns", "Musical rhythm", "Hidden assumptions"],
    answerIndex: 2,
    explanation: "Socratic questioning tests assumptions and reveals gaps in a person's reasoning.",
  },
  {
    id: 14,
    chapter: "Chapter 14",
    topic: "Optics",
    question: "A rainbow appears because sunlight is split by what?",
    options: ["Magnets", "Water droplets", "Sound waves"],
    answerIndex: 1,
    explanation: "Water droplets refract and separate sunlight into different colors.",
  },
  {
    id: 15,
    chapter: "Chapter 15",
    topic: "Geometry",
    question: "How many degrees are inside a triangle?",
    options: ["180", "90", "360"],
    answerIndex: 0,
    explanation: "The interior angles of any flat triangle add up to 180 degrees.",
  },
  {
    id: 16,
    chapter: "Chapter 16",
    topic: "Evolution",
    question: "Natural selection favors traits that help organisms do what?",
    options: ["Become perfect", "Avoid all change", "Survive and reproduce"],
    answerIndex: 2,
    explanation: "Traits that improve survival or reproduction tend to become more common over generations.",
  },
  {
    id: 17,
    chapter: "Chapter 17",
    topic: "Ethics",
    question: "Utilitarianism usually asks which question?",
    options: ["What is the oldest rule?", "What creates the most overall good?", "What looks expensive?"],
    answerIndex: 1,
    explanation: "Utilitarian thinking judges actions by their consequences for overall well-being.",
  },
  {
    id: 18,
    chapter: "Chapter 18",
    topic: "Gravity",
    question: "On Earth, gravity pulls objects in which direction?",
    options: ["Toward the Moon", "Sideways forever", "Toward Earth's center"],
    answerIndex: 2,
    explanation: "Gravity pulls mass toward mass, so near Earth it pulls objects toward Earth's center.",
  },
  {
    id: 19,
    chapter: "Chapter 19",
    topic: "Fractions",
    question: "Which is the same as one half?",
    options: ["2/4", "1/3", "3/2"],
    answerIndex: 0,
    explanation: "2/4 simplifies to 1/2 because both numerator and denominator divide by 2.",
  },
  {
    id: 20,
    chapter: "Chapter 20",
    topic: "Cells",
    question: "What is often called the powerhouse of the cell?",
    options: ["Rib cage", "Mitochondrion", "Neuron"],
    answerIndex: 1,
    explanation: "Mitochondria help cells turn fuel into usable energy.",
  },
  {
    id: 21,
    chapter: "Chapter 21",
    topic: "Logic",
    question: "If an argument's conclusion follows from its premises, the argument is what?",
    options: ["Loud", "Biological", "Valid"],
    answerIndex: 2,
    explanation: "Validity is about whether the conclusion follows logically from the premises.",
  },
  {
    id: 22,
    chapter: "Chapter 22",
    topic: "Electricity",
    question: "Electric current is the flow of what?",
    options: ["Temperature", "Electric charge", "Empty space"],
    answerIndex: 1,
    explanation: "Current measures how much electric charge flows through a point over time.",
  },
  {
    id: 23,
    chapter: "Chapter 23",
    topic: "Calculus",
    question: "A derivative tells you a function's what?",
    options: ["Rate of change", "Favorite number", "Color"],
    answerIndex: 0,
    explanation: "The derivative measures how quickly a function changes at a point.",
  },
  {
    id: 24,
    chapter: "Chapter 24",
    topic: "Ecology",
    question: "A food chain usually starts with organisms that get energy from what?",
    options: ["Plastic", "Wi-Fi", "Sunlight"],
    answerIndex: 2,
    explanation: "Producers like plants capture sunlight and form the base of many food chains.",
  },
  {
    id: 25,
    chapter: "Chapter 25",
    topic: "Epistemology",
    question: "Epistemology is the branch of philosophy that studies what?",
    options: ["Volcanoes", "Knowledge", "Cell division"],
    answerIndex: 1,
    explanation: "Epistemology asks what knowledge is and how we can justify what we believe.",
  },
  {
    id: 26,
    chapter: "Chapter 26",
    topic: "Relativity",
    question: "Einstein's relativity connects space with what?",
    options: ["Sugar", "Photosynthesis", "Time"],
    answerIndex: 2,
    explanation: "Relativity treats space and time as linked parts of spacetime.",
  },
  {
    id: 27,
    chapter: "Chapter 27",
    topic: "Statistics",
    question: "The average of 2, 4, and 6 is what?",
    options: ["4", "6", "12"],
    answerIndex: 0,
    explanation: "Add the numbers to get 12, then divide by 3 to get 4.",
  },
  {
    id: 28,
    chapter: "Chapter 28",
    topic: "Genetics",
    question: "Genes are passed from parents to offspring through what?",
    options: ["Evaporation", "Inheritance", "Friction"],
    answerIndex: 1,
    explanation: "Inheritance is the transmission of genetic information from one generation to the next.",
  },
  {
    id: 29,
    chapter: "Chapter 29",
    topic: "Stoicism",
    question: "Stoicism often teaches you to focus on what?",
    options: ["Winning every argument", "Predicting lottery numbers", "What you can control"],
    answerIndex: 2,
    explanation: "Stoic practice separates what is up to you from what is not.",
  },
  {
    id: 30,
    chapter: "Chapter 30",
    topic: "Waves",
    question: "Sound travels through air as what?",
    options: ["A shadow", "A wave", "A chemical bond"],
    answerIndex: 1,
    explanation: "Sound is a pressure wave moving through a medium like air.",
  },
  {
    id: 31,
    chapter: "Chapter 31",
    topic: "Number Theory",
    question: "A prime number has exactly how many positive factors?",
    options: ["Two", "One", "Infinitely many"],
    answerIndex: 0,
    explanation: "A prime number is divisible only by 1 and itself.",
  },
  {
    id: 32,
    chapter: "Chapter 32",
    topic: "Photosynthesis",
    question: "Plants use photosynthesis to turn sunlight into what kind of stored energy?",
    options: ["Gravity", "Static noise", "Chemical energy"],
    answerIndex: 2,
    explanation: "Photosynthesis stores energy in chemical bonds, especially in sugars.",
  },
  {
    id: 33,
    chapter: "Chapter 33",
    topic: "Metaphysics",
    question: "Metaphysics asks questions about what?",
    options: ["How to boil pasta", "What exists", "Blood pressure"],
    answerIndex: 1,
    explanation: "Metaphysics studies reality, existence, identity, causation, and related ideas.",
  },
  {
    id: 34,
    chapter: "Chapter 34",
    topic: "Thermodynamics",
    question: "Heat usually flows naturally from hot objects to what?",
    options: ["Colder objects", "Louder objects", "Smaller numbers"],
    answerIndex: 0,
    explanation: "Heat naturally flows from higher temperature regions to lower temperature regions.",
  },
  {
    id: 35,
    chapter: "Chapter 35",
    topic: "Graphs",
    question: "On a graph, the x-axis usually runs which way?",
    options: ["Left to right", "Only upward", "In a circle"],
    answerIndex: 0,
    explanation: "The x-axis is the horizontal axis, usually read left to right.",
  },
  {
    id: 36,
    chapter: "Chapter 36",
    topic: "Neuroscience",
    question: "Neurons mainly help the body transmit what?",
    options: ["Bones", "Oxygen bubbles", "Signals"],
    answerIndex: 2,
    explanation: "Neurons communicate with electrical and chemical signals across the nervous system.",
  },
  {
    id: 37,
    chapter: "Chapter 37",
    topic: "Existentialism",
    question: "Existentialism often focuses on freedom and what else?",
    options: ["Plate tectonics", "Responsibility", "Prime numbers"],
    answerIndex: 1,
    explanation: "Existentialist thinkers often connect human freedom with responsibility for one's choices.",
  },
  {
    id: 38,
    chapter: "Chapter 38",
    topic: "Astronomy",
    question: "The Earth orbits what?",
    options: ["Mars", "A battery", "The Sun"],
    answerIndex: 2,
    explanation: "Earth is a planet in orbit around the Sun.",
  },
  {
    id: 39,
    chapter: "Chapter 39",
    topic: "Percentages",
    question: "What is 50% of 20?",
    options: ["10", "50", "20"],
    answerIndex: 0,
    explanation: "50% means one half, and half of 20 is 10.",
  },
  {
    id: 40,
    chapter: "Chapter 40",
    topic: "Immunity",
    question: "Vaccines help the immune system recognize what?",
    options: ["The color blue", "A pathogen or threat", "Magnetic north"],
    answerIndex: 1,
    explanation: "Vaccines train immune memory so the body can respond faster to a real threat.",
  },
  {
    id: 41,
    chapter: "Chapter 41",
    topic: "Algebra",
    question: "If 2x = 18, what is x?",
    options: ["9", "16", "36"],
    answerIndex: 0,
    explanation: "Divide both sides by 2 and x = 9.",
  },
  {
    id: 42,
    chapter: "Chapter 42",
    topic: "Cell Biology",
    question: "Which cell structure controls what enters and leaves the cell?",
    options: ["Tooth enamel", "Cell membrane", "Spinal cord"],
    answerIndex: 1,
    explanation: "The cell membrane is a selective boundary around the cell.",
  },
  {
    id: 43,
    chapter: "Chapter 43",
    topic: "Philosophy",
    question: "A claim that can be tested by observation is usually called what?",
    options: ["Decorative", "Circular", "Empirical"],
    answerIndex: 2,
    explanation: "Empirical claims are grounded in observation or experience.",
  },
  {
    id: 44,
    chapter: "Chapter 44",
    topic: "Motion",
    question: "Speed tells you distance divided by what?",
    options: ["Mass", "Time", "Temperature"],
    answerIndex: 1,
    explanation: "Speed is distance traveled per unit of time.",
  },
  {
    id: 45,
    chapter: "Chapter 45",
    topic: "Geometry",
    question: "The area of a rectangle is length times what?",
    options: ["Width", "Volume", "Angle"],
    answerIndex: 0,
    explanation: "Rectangle area is length multiplied by width.",
  },
  {
    id: 46,
    chapter: "Chapter 46",
    topic: "Ecology",
    question: "An organism's role in an ecosystem is called its what?",
    options: ["Password", "Velocity", "Niche"],
    answerIndex: 2,
    explanation: "A niche describes how an organism fits into and uses its environment.",
  },
  {
    id: 47,
    chapter: "Chapter 47",
    topic: "Ethics",
    question: "A moral dilemma usually involves what?",
    options: ["Competing values", "Only one possible answer", "No human choices"],
    answerIndex: 0,
    explanation: "Dilemmas are hard because different values or duties can pull against each other.",
  },
  {
    id: 48,
    chapter: "Chapter 48",
    topic: "Energy",
    question: "Kinetic energy is energy of what?",
    options: ["Color", "Motion", "Grammar"],
    answerIndex: 1,
    explanation: "Kinetic energy is the energy an object has because it is moving.",
  },
  {
    id: 49,
    chapter: "Chapter 49",
    topic: "Probability",
    question: "A probability of 1 means an event is what?",
    options: ["Certain", "Impossible", "Half likely"],
    answerIndex: 0,
    explanation: "Probability 1 means the event is certain under the model.",
  },
  {
    id: 50,
    chapter: "Chapter 50",
    topic: "Calculus",
    question: "If position is changing, the derivative of position gives what?",
    options: ["DNA", "Velocity", "Logical validity"],
    answerIndex: 1,
    explanation: "Velocity is the rate of change of position with respect to time.",
  },
  {
    id: 51,
    chapter: "Chapter 51",
    topic: "Genetics",
    question: "A recessive trait usually appears when an organism has how many recessive copies?",
    options: ["Zero", "Only sunlight", "Two"],
    answerIndex: 2,
    explanation: "For many simple traits, a recessive version appears when both gene copies are recessive.",
  },
  {
    id: 52,
    chapter: "Chapter 52",
    topic: "Epistemology",
    question: "The classic definition of knowledge is justified true what?",
    options: ["Motion", "Belief", "Protein"],
    answerIndex: 1,
    explanation: "A traditional account says knowledge is justified true belief, though philosophers debate it.",
  },
  {
    id: 53,
    chapter: "Chapter 53",
    topic: "Thermodynamics",
    question: "In a closed system, total energy is generally what?",
    options: ["Conserved", "Forgotten", "Squared"],
    answerIndex: 0,
    explanation: "The first law of thermodynamics says energy is conserved, though it can change form.",
  },
  {
    id: 54,
    chapter: "Chapter 54",
    topic: "Linear Algebra",
    question: "A vector usually represents magnitude plus what?",
    options: ["Smell", "Species", "Direction"],
    answerIndex: 2,
    explanation: "Vectors encode both size and direction, such as force or velocity.",
  },
  {
    id: 55,
    chapter: "Chapter 55",
    topic: "Evolution",
    question: "Genetic drift has the strongest effect in which populations?",
    options: ["Infinitely large populations", "Small populations", "Only machines"],
    answerIndex: 1,
    explanation: "Random changes in gene frequencies matter more when populations are small.",
  },
  {
    id: 56,
    chapter: "Chapter 56",
    topic: "Logic",
    question: "A contradiction says a statement is both true and what?",
    options: ["False", "Blue", "Massive"],
    answerIndex: 0,
    explanation: "A contradiction asserts incompatible claims, such as P and not-P.",
  },
  {
    id: 57,
    chapter: "Chapter 57",
    topic: "Quantum Physics",
    question: "Before measurement, a quantum state is often described as a superposition of what?",
    options: ["Tiny planets", "Moral duties", "Possible outcomes"],
    answerIndex: 2,
    explanation: "Superposition means the state can combine multiple possible measurement outcomes.",
  },
  {
    id: 58,
    chapter: "Chapter 58",
    topic: "Number Theory",
    question: "If two numbers share no common factor besides 1, they are called what?",
    options: ["Parallel", "Coprime", "Endothermic"],
    answerIndex: 1,
    explanation: "Coprime numbers have greatest common divisor 1.",
  },
  {
    id: 59,
    chapter: "Chapter 59",
    topic: "Physiology",
    question: "Homeostasis means an organism tends to maintain what?",
    options: ["Internal stability", "Maximum speed", "Perfect silence"],
    answerIndex: 0,
    explanation: "Homeostasis keeps internal conditions like temperature or pH within workable ranges.",
  },
  {
    id: 60,
    chapter: "Chapter 60",
    topic: "Philosophy of Mind",
    question: "Dualism claims mind and body are what kind of things?",
    options: ["Identical triangles", "Food chains", "Distinct"],
    answerIndex: 2,
    explanation: "Dualism holds that mental and physical reality are fundamentally distinct in some way.",
  },
  {
    id: 61,
    chapter: "Chapter 61",
    topic: "Relativity",
    question: "Special relativity says the speed of light in vacuum is what for all inertial observers?",
    options: ["Random", "The same", "Zero"],
    answerIndex: 1,
    explanation: "A core postulate is that all inertial observers measure the same vacuum light speed.",
  },
  {
    id: 62,
    chapter: "Chapter 62",
    topic: "Functions",
    question: "If f(x) = x^2, what is f(3)?",
    options: ["9", "6", "3"],
    answerIndex: 0,
    explanation: "Substitute 3 for x: 3^2 = 9.",
  },
  {
    id: 63,
    chapter: "Chapter 63",
    topic: "Molecular Biology",
    question: "During transcription, DNA information is copied into what?",
    options: ["Bone", "Light", "RNA"],
    answerIndex: 2,
    explanation: "Transcription copies genetic information from DNA into RNA.",
  },
  {
    id: 64,
    chapter: "Chapter 64",
    topic: "Ethics",
    question: "Deontology judges actions mainly by duties and what?",
    options: ["Rules", "Calories", "Acceleration"],
    answerIndex: 0,
    explanation: "Deontological ethics emphasizes duties, rights, and rules rather than only outcomes.",
  },
  {
    id: 65,
    chapter: "Chapter 65",
    topic: "Electromagnetism",
    question: "A changing magnetic field can induce what in a wire?",
    options: ["DNA mutation", "Electric current", "A syllogism"],
    answerIndex: 1,
    explanation: "Electromagnetic induction can generate current from changing magnetic fields.",
  },
  {
    id: 66,
    chapter: "Chapter 66",
    topic: "Probability",
    question: "Two independent events do not affect each other's what?",
    options: ["Probabilities", "Masses", "Definitions"],
    answerIndex: 0,
    explanation: "Independence means knowing one event happened does not change the probability of the other.",
  },
  {
    id: 67,
    chapter: "Chapter 67",
    topic: "Ecology",
    question: "A keystone species has an unusually large effect on what?",
    options: ["Its spelling", "Planetary orbit", "Its ecosystem"],
    answerIndex: 2,
    explanation: "Keystone species strongly shape ecosystem structure relative to their abundance.",
  },
  {
    id: 68,
    chapter: "Chapter 68",
    topic: "Metaphysics",
    question: "The problem of personal identity asks what makes you the same person across what?",
    options: ["Time", "Temperature", "Tax brackets"],
    answerIndex: 0,
    explanation: "Personal identity asks what preserves sameness of a person over time and change.",
  },
  {
    id: 69,
    chapter: "Chapter 69",
    topic: "Mechanics",
    question: "Momentum equals mass times what?",
    options: ["Entropy", "Velocity", "Belief"],
    answerIndex: 1,
    explanation: "Linear momentum is p = mv, mass multiplied by velocity.",
  },
  {
    id: 70,
    chapter: "Chapter 70",
    topic: "Geometry",
    question: "In a right triangle, the longest side is called the what?",
    options: ["Hypotenuse", "Derivative", "Organelle"],
    answerIndex: 0,
    explanation: "The hypotenuse is opposite the right angle and is the longest side.",
  },
  {
    id: 71,
    chapter: "Chapter 71",
    topic: "Immunology",
    question: "Antibodies bind specifically to what on pathogens?",
    options: ["Exponents", "Planets", "Antigens"],
    answerIndex: 2,
    explanation: "Antibodies recognize antigens, molecular features associated with threats.",
  },
  {
    id: 72,
    chapter: "Chapter 72",
    topic: "Political Philosophy",
    question: "A social contract theory explains political authority through what?",
    options: ["Agreement or consent", "Photosynthesis", "Prime factorization"],
    answerIndex: 0,
    explanation: "Social contract theories ground political order in some form of agreement or consent.",
  },
  {
    id: 73,
    chapter: "Chapter 73",
    topic: "Astrophysics",
    question: "A black hole's event horizon marks the boundary beyond which what cannot escape?",
    options: ["Arithmetic", "Light", "Bacteria"],
    answerIndex: 1,
    explanation: "Inside the event horizon, escape velocity exceeds the speed of light.",
  },
  {
    id: 74,
    chapter: "Chapter 74",
    topic: "Logarithms",
    question: "A logarithm answers which question?",
    options: ["What exponent gives this number?", "What organ pumps blood?", "What is moral courage?"],
    answerIndex: 0,
    explanation: "log_b(x) asks what exponent on base b produces x.",
  },
  {
    id: 75,
    chapter: "Chapter 75",
    topic: "Biochemistry",
    question: "Enzymes usually speed reactions by lowering what?",
    options: ["Genetic code", "Logical validity", "Activation energy"],
    answerIndex: 2,
    explanation: "Enzymes make reactions easier by lowering the activation energy barrier.",
  },
  {
    id: 76,
    chapter: "Chapter 76",
    topic: "Aesthetics",
    question: "Aesthetics is the branch of philosophy focused on beauty and what?",
    options: ["Art", "Electric charge", "Cell membranes"],
    answerIndex: 0,
    explanation: "Aesthetics studies beauty, art, taste, and aesthetic experience.",
  },
  {
    id: 77,
    chapter: "Chapter 77",
    topic: "Waves",
    question: "Wave frequency measures how many cycles happen per what?",
    options: ["Kilogram", "Second", "Premise"],
    answerIndex: 1,
    explanation: "Frequency is cycles per second, measured in hertz.",
  },
  {
    id: 78,
    chapter: "Chapter 78",
    topic: "Statistics",
    question: "A correlation of zero means two variables have no what kind of relationship?",
    options: ["Linear", "Biological", "Ethical"],
    answerIndex: 0,
    explanation: "Zero correlation means no linear relationship, though other patterns may still exist.",
  },
  {
    id: 79,
    chapter: "Chapter 79",
    topic: "Evolution",
    question: "Convergent evolution produces similar traits in species with different what?",
    options: ["Temperatures", "Equations", "Ancestries"],
    answerIndex: 2,
    explanation: "Different lineages can evolve similar solutions under similar pressures.",
  },
  {
    id: 80,
    chapter: "Chapter 80",
    topic: "Existentialism",
    question: "When Sartre says existence precedes essence, he means humans first exist and then what?",
    options: ["Define themselves through choices", "Become triangles", "Lose all biology"],
    answerIndex: 0,
    explanation: "The phrase means people are not born with a fixed essence; they shape themselves through action.",
  },
  {
    id: 81,
    chapter: "Chapter 81",
    topic: "Optics",
    question: "Refraction happens when light changes direction because it changes what?",
    options: ["Moral status", "Speed in a medium", "Chromosome count"],
    answerIndex: 1,
    explanation: "Light bends when its speed changes as it passes between media.",
  },
  {
    id: 82,
    chapter: "Chapter 82",
    topic: "Sequences",
    question: "In a geometric sequence, each term is multiplied by a constant called the what?",
    options: ["Common ratio", "Cell nucleus", "Magnetic pole"],
    answerIndex: 0,
    explanation: "A geometric sequence uses a fixed multiplier, the common ratio.",
  },
  {
    id: 83,
    chapter: "Chapter 83",
    topic: "Neuroscience",
    question: "A synapse is a junction where neurons do what?",
    options: ["Orbit", "Factor polynomials", "Communicate"],
    answerIndex: 2,
    explanation: "Synapses allow neurons to pass signals to other neurons or cells.",
  },
  {
    id: 84,
    chapter: "Chapter 84",
    topic: "Virtue Ethics",
    question: "Virtue ethics focuses most on developing what?",
    options: ["Character", "Speed", "Mitochondria"],
    answerIndex: 0,
    explanation: "Virtue ethics emphasizes character traits like courage, honesty, and practical wisdom.",
  },
  {
    id: 85,
    chapter: "Chapter 85",
    topic: "Electric Circuits",
    question: "Ohm's law relates voltage, current, and what?",
    options: ["Natural selection", "Resistance", "Certainty"],
    answerIndex: 1,
    explanation: "Ohm's law is V = IR, linking voltage, current, and resistance.",
  },
  {
    id: 86,
    chapter: "Chapter 86",
    topic: "Topology",
    question: "Topology studies properties preserved under continuous what?",
    options: ["Deformation", "Digestion", "Acceleration"],
    answerIndex: 0,
    explanation: "Topology cares about properties that survive stretching or bending without tearing or gluing.",
  },
  {
    id: 87,
    chapter: "Chapter 87",
    topic: "Microbiology",
    question: "Bacteria are usually classified as what type of cells?",
    options: ["Philosophical", "Triangular", "Prokaryotic"],
    answerIndex: 2,
    explanation: "Bacteria are prokaryotes, meaning they lack a membrane-bound nucleus.",
  },
  {
    id: 88,
    chapter: "Chapter 88",
    topic: "Philosophy of Science",
    question: "Falsifiability means a scientific claim could in principle be shown what?",
    options: ["False", "Expensive", "Photosynthetic"],
    answerIndex: 0,
    explanation: "A falsifiable claim makes risky predictions that evidence could contradict.",
  },
  {
    id: 89,
    chapter: "Chapter 89",
    topic: "Fluids",
    question: "Buoyant force acts opposite to what?",
    options: ["Knowledge", "Gravity", "Inheritance"],
    answerIndex: 1,
    explanation: "Buoyancy pushes upward against the downward pull of gravity.",
  },
  {
    id: 90,
    chapter: "Chapter 90",
    topic: "Set Theory",
    question: "The intersection of two sets contains elements that are where?",
    options: ["In both sets", "In neither set", "Only imaginary"],
    answerIndex: 0,
    explanation: "An intersection keeps exactly the elements shared by both sets.",
  },
  {
    id: 91,
    chapter: "Chapter 91",
    topic: "Anatomy",
    question: "Red blood cells mainly transport what?",
    options: ["Sound", "Theorems", "Oxygen"],
    answerIndex: 2,
    explanation: "Red blood cells carry oxygen using hemoglobin.",
  },
  {
    id: 92,
    chapter: "Chapter 92",
    topic: "Moral Philosophy",
    question: "The trolley problem is used to test intuitions about consequences and what?",
    options: ["Moral rules", "Cell walls", "Square roots"],
    answerIndex: 0,
    explanation: "The trolley problem contrasts outcome-focused reasoning with rule- or duty-focused reasoning.",
  },
  {
    id: 93,
    chapter: "Chapter 93",
    topic: "Cosmology",
    question: "The expanding universe is supported by galaxies showing what kind of shift?",
    options: ["Mood shift", "Redshift", "Tax shift"],
    answerIndex: 1,
    explanation: "Distant galaxies tend to be redshifted, which indicates expansion of space.",
  },
  {
    id: 94,
    chapter: "Chapter 94",
    topic: "Differential Equations",
    question: "A differential equation relates a function to its what?",
    options: ["Derivatives", "Organs", "Virtues"],
    answerIndex: 0,
    explanation: "Differential equations describe how quantities change by involving derivatives.",
  },
  {
    id: 95,
    chapter: "Chapter 95",
    topic: "Genomics",
    question: "A mutation is a change in what?",
    options: ["Gravitational mass", "Logical form", "DNA sequence"],
    answerIndex: 2,
    explanation: "A mutation changes the sequence of genetic material.",
  },
  {
    id: 96,
    chapter: "Chapter 96",
    topic: "Phenomenology",
    question: "Phenomenology studies experience as it is what?",
    options: ["Lived or perceived", "Electrically charged", "Genetically copied"],
    answerIndex: 0,
    explanation: "Phenomenology investigates first-person experience and how things appear to consciousness.",
  },
  {
    id: 97,
    chapter: "Chapter 97",
    topic: "Nuclear Physics",
    question: "Nuclear fission splits a heavy nucleus into what?",
    options: ["Moral claims", "Smaller nuclei", "Prime factors only"],
    answerIndex: 1,
    explanation: "Fission releases energy when a heavy atomic nucleus splits into smaller nuclei.",
  },
  {
    id: 98,
    chapter: "Chapter 98",
    topic: "Trigonometry",
    question: "In a right triangle, sine is opposite over what?",
    options: ["Hypotenuse", "Adjacent", "Genome"],
    answerIndex: 0,
    explanation: "For an acute angle in a right triangle, sine equals opposite side divided by hypotenuse.",
  },
  {
    id: 99,
    chapter: "Chapter 99",
    topic: "Biology",
    question: "Meiosis produces cells with half the usual number of what?",
    options: ["Forces", "Premises", "Chromosomes"],
    answerIndex: 2,
    explanation: "Meiosis creates gametes with half the chromosome number of body cells.",
  },
  {
    id: 100,
    chapter: "Chapter 100",
    topic: "Philosophy",
    question: "The is-ought problem says facts alone do not automatically give you what?",
    options: ["Moral conclusions", "Electric current", "Cell division"],
    answerIndex: 0,
    explanation: "Hume's is-ought problem warns that descriptive facts do not by themselves entail normative conclusions.",
  },
];

export function getQuizQuestion(id: number) {
  return quizQuestions.find((question) => question.id === id);
}
