export interface QuizQuestion {
  id: number;
  chapter: string;
  topic: string;
  question: string;
  options: [string, string, string];
  answerIndex: number;
  explanation: string;
}

export const quizQuestions: QuizQuestion[] = [
  {
    id: 1,
    chapter: "Chapter 1",
    topic: "Entropy",
    question: "If a room gets messier over time, which idea is it hinting at?",
    options: ["Entropy tends to increase", "Gravity turns off", "Energy disappears"],
    answerIndex: 0,
    explanation: "Entropy is a way to describe how many messy, spread-out arrangements are available.",
  },
  {
    id: 2,
    chapter: "Chapter 2",
    topic: "Blockchain",
    question: "What does a blockchain transaction signature prove?",
    options: ["The receiver is online", "The sender approved it", "The coin has weight"],
    answerIndex: 1,
    explanation: "A valid signature proves the transaction was authorized by the holder of the private key.",
  },
  {
    id: 3,
    chapter: "Chapter 3",
    topic: "AI",
    question: "What is the main job of training an AI model?",
    options: ["Memorize every website", "Turn code into electricity", "Adjust patterns from examples"],
    answerIndex: 2,
    explanation: "Training updates model parameters so it captures useful patterns in examples.",
  },
  {
    id: 4,
    chapter: "Chapter 4",
    topic: "Physics",
    question: "When you push a wall and it pushes back, which law are you seeing?",
    options: ["Pythagoras' theorem", "Newton's third law", "Moore's law"],
    answerIndex: 1,
    explanation: "Newton's third law says forces come in equal and opposite pairs.",
  },
  {
    id: 5,
    chapter: "Chapter 5",
    topic: "Proofs",
    question: "What makes a mathematical proof convincing?",
    options: ["Each step follows logically", "It uses big words", "It is written in red ink"],
    answerIndex: 0,
    explanation: "A proof works when every step follows from accepted assumptions or previous steps.",
  },
  {
    id: 6,
    chapter: "Chapter 6",
    topic: "Memory",
    question: "Which habit usually helps memory most?",
    options: ["Rereading once quickly", "Changing font color", "Testing yourself later"],
    answerIndex: 2,
    explanation: "Retrieval practice strengthens memory because you reconstruct the idea yourself.",
  },
  {
    id: 7,
    chapter: "Chapter 7",
    topic: "Markets",
    question: "If demand rises while supply stays the same, price usually does what?",
    options: ["Goes up", "Always goes to zero", "Becomes illegal"],
    answerIndex: 0,
    explanation: "More buyers competing for the same supply usually pushes price upward.",
  },
  {
    id: 8,
    chapter: "Chapter 8",
    topic: "Code",
    question: "What does a loop help a program do?",
    options: ["Repeat steps", "Hide the keyboard", "Make pixels heavier"],
    answerIndex: 0,
    explanation: "A loop repeats instructions until a condition stops it or the sequence ends.",
  },
  {
    id: 9,
    chapter: "Chapter 9",
    topic: "Probability",
    question: "A fair coin lands heads five times. What is the next flip most likely to be?",
    options: ["Definitely tails", "Still 50/50", "Definitely heads"],
    answerIndex: 1,
    explanation: "Past flips do not change the next flip of a fair coin; it remains 50/50.",
  },
  {
    id: 10,
    chapter: "Chapter 10",
    topic: "Learning",
    question: "What is an aha moment usually a sign of?",
    options: ["A mental model clicked", "You are done forever", "The question was fake"],
    answerIndex: 0,
    explanation: "An aha moment means pieces reorganized into a model you can carry forward.",
  },
  {
    id: 11,
    chapter: "Chapter 11",
    topic: "Algebra",
    question: "If x + 3 = 7, what is x?",
    options: ["4", "10", "21"],
    answerIndex: 0,
    explanation: "Subtract 3 from both sides and x = 4.",
  },
  {
    id: 12,
    chapter: "Chapter 12",
    topic: "Biology",
    question: "Which molecule carries genetic instructions in most living things?",
    options: ["Salt", "DNA", "Cholesterol"],
    answerIndex: 1,
    explanation: "DNA stores genetic instructions used by cells to build and regulate living systems.",
  },
  {
    id: 13,
    chapter: "Chapter 13",
    topic: "Philosophy",
    question: "Socrates is famous for asking questions mainly to expose what?",
    options: ["Weather patterns", "Musical rhythm", "Hidden assumptions"],
    answerIndex: 2,
    explanation: "Socratic questioning tests assumptions and reveals gaps in a person's reasoning.",
  },
  {
    id: 14,
    chapter: "Chapter 14",
    topic: "Optics",
    question: "A rainbow appears because sunlight is split by what?",
    options: ["Magnets", "Water droplets", "Sound waves"],
    answerIndex: 1,
    explanation: "Water droplets refract and separate sunlight into different colors.",
  },
  {
    id: 15,
    chapter: "Chapter 15",
    topic: "Geometry",
    question: "How many degrees are inside a triangle?",
    options: ["180", "90", "360"],
    answerIndex: 0,
    explanation: "The interior angles of any flat triangle add up to 180 degrees.",
  },
  {
    id: 16,
    chapter: "Chapter 16",
    topic: "Evolution",
    question: "Natural selection favors traits that help organisms do what?",
    options: ["Become perfect", "Avoid all change", "Survive and reproduce"],
    answerIndex: 2,
    explanation: "Traits that improve survival or reproduction tend to become more common over generations.",
  },
  {
    id: 17,
    chapter: "Chapter 17",
    topic: "Ethics",
    question: "Utilitarianism usually asks which question?",
    options: ["What is the oldest rule?", "What creates the most overall good?", "What looks expensive?"],
    answerIndex: 1,
    explanation: "Utilitarian thinking judges actions by their consequences for overall well-being.",
  },
  {
    id: 18,
    chapter: "Chapter 18",
    topic: "Gravity",
    question: "On Earth, gravity pulls objects in which direction?",
    options: ["Toward the Moon", "Sideways forever", "Toward Earth's center"],
    answerIndex: 2,
    explanation: "Gravity pulls mass toward mass, so near Earth it pulls objects toward Earth's center.",
  },
  {
    id: 19,
    chapter: "Chapter 19",
    topic: "Fractions",
    question: "Which is the same as one half?",
    options: ["2/4", "1/3", "3/2"],
    answerIndex: 0,
    explanation: "2/4 simplifies to 1/2 because both numerator and denominator divide by 2.",
  },
  {
    id: 20,
    chapter: "Chapter 20",
    topic: "Cells",
    question: "What is often called the powerhouse of the cell?",
    options: ["Rib cage", "Mitochondrion", "Neuron"],
    answerIndex: 1,
    explanation: "Mitochondria help cells turn fuel into usable energy.",
  },
  {
    id: 21,
    chapter: "Chapter 21",
    topic: "Logic",
    question: "If an argument's conclusion follows from its premises, the argument is what?",
    options: ["Loud", "Biological", "Valid"],
    answerIndex: 2,
    explanation: "Validity is about whether the conclusion follows logically from the premises.",
  },
  {
    id: 22,
    chapter: "Chapter 22",
    topic: "Electricity",
    question: "Electric current is the flow of what?",
    options: ["Temperature", "Electric charge", "Empty space"],
    answerIndex: 1,
    explanation: "Current measures how much electric charge flows through a point over time.",
  },
  {
    id: 23,
    chapter: "Chapter 23",
    topic: "Calculus",
    question: "A derivative tells you a function's what?",
    options: ["Rate of change", "Favorite number", "Color"],
    answerIndex: 0,
    explanation: "The derivative measures how quickly a function changes at a point.",
  },
  {
    id: 24,
    chapter: "Chapter 24",
    topic: "Ecology",
    question: "A food chain usually starts with organisms that get energy from what?",
    options: ["Plastic", "Wi-Fi", "Sunlight"],
    answerIndex: 2,
    explanation: "Producers like plants capture sunlight and form the base of many food chains.",
  },
  {
    id: 25,
    chapter: "Chapter 25",
    topic: "Epistemology",
    question: "Epistemology is the branch of philosophy that studies what?",
    options: ["Volcanoes", "Knowledge", "Cell division"],
    answerIndex: 1,
    explanation: "Epistemology asks what knowledge is and how we can justify what we believe.",
  },
  {
    id: 26,
    chapter: "Chapter 26",
    topic: "Relativity",
    question: "Einstein's relativity connects space with what?",
    options: ["Sugar", "Photosynthesis", "Time"],
    answerIndex: 2,
    explanation: "Relativity treats space and time as linked parts of spacetime.",
  },
  {
    id: 27,
    chapter: "Chapter 27",
    topic: "Statistics",
    question: "The average of 2, 4, and 6 is what?",
    options: ["4", "6", "12"],
    answerIndex: 0,
    explanation: "Add the numbers to get 12, then divide by 3 to get 4.",
  },
  {
    id: 28,
    chapter: "Chapter 28",
    topic: "Genetics",
    question: "Genes are passed from parents to offspring through what?",
    options: ["Evaporation", "Inheritance", "Friction"],
    answerIndex: 1,
    explanation: "Inheritance is the transmission of genetic information from one generation to the next.",
  },
  {
    id: 29,
    chapter: "Chapter 29",
    topic: "Stoicism",
    question: "Stoicism often teaches you to focus on what?",
    options: ["Winning every argument", "Predicting lottery numbers", "What you can control"],
    answerIndex: 2,
    explanation: "Stoic practice separates what is up to you from what is not.",
  },
  {
    id: 30,
    chapter: "Chapter 30",
    topic: "Waves",
    question: "Sound travels through air as what?",
    options: ["A shadow", "A wave", "A chemical bond"],
    answerIndex: 1,
    explanation: "Sound is a pressure wave moving through a medium like air.",
  },
  {
    id: 31,
    chapter: "Chapter 31",
    topic: "Number Theory",
    question: "A prime number has exactly how many positive factors?",
    options: ["Two", "One", "Infinitely many"],
    answerIndex: 0,
    explanation: "A prime number is divisible only by 1 and itself.",
  },
  {
    id: 32,
    chapter: "Chapter 32",
    topic: "Photosynthesis",
    question: "Plants use photosynthesis to turn sunlight into what kind of stored energy?",
    options: ["Gravity", "Static noise", "Chemical energy"],
    answerIndex: 2,
    explanation: "Photosynthesis stores energy in chemical bonds, especially in sugars.",
  },
  {
    id: 33,
    chapter: "Chapter 33",
    topic: "Metaphysics",
    question: "Metaphysics asks questions about what?",
    options: ["How to boil pasta", "What exists", "Blood pressure"],
    answerIndex: 1,
    explanation: "Metaphysics studies reality, existence, identity, causation, and related ideas.",
  },
  {
    id: 34,
    chapter: "Chapter 34",
    topic: "Thermodynamics",
    question: "Heat usually flows naturally from hot objects to what?",
    options: ["Colder objects", "Louder objects", "Smaller numbers"],
    answerIndex: 0,
    explanation: "Heat naturally flows from higher temperature regions to lower temperature regions.",
  },
  {
    id: 35,
    chapter: "Chapter 35",
    topic: "Graphs",
    question: "On a graph, the x-axis usually runs which way?",
    options: ["Left to right", "Only upward", "In a circle"],
    answerIndex: 0,
    explanation: "The x-axis is the horizontal axis, usually read left to right.",
  },
  {
    id: 36,
    chapter: "Chapter 36",
    topic: "Neuroscience",
    question: "Neurons mainly help the body transmit what?",
    options: ["Bones", "Oxygen bubbles", "Signals"],
    answerIndex: 2,
    explanation: "Neurons communicate with electrical and chemical signals across the nervous system.",
  },
  {
    id: 37,
    chapter: "Chapter 37",
    topic: "Existentialism",
    question: "Existentialism often focuses on freedom and what else?",
    options: ["Plate tectonics", "Responsibility", "Prime numbers"],
    answerIndex: 1,
    explanation: "Existentialist thinkers often connect human freedom with responsibility for one's choices.",
  },
  {
    id: 38,
    chapter: "Chapter 38",
    topic: "Astronomy",
    question: "The Earth orbits what?",
    options: ["Mars", "A battery", "The Sun"],
    answerIndex: 2,
    explanation: "Earth is a planet in orbit around the Sun.",
  },
  {
    id: 39,
    chapter: "Chapter 39",
    topic: "Percentages",
    question: "What is 50% of 20?",
    options: ["10", "50", "20"],
    answerIndex: 0,
    explanation: "50% means one half, and half of 20 is 10.",
  },
  {
    id: 40,
    chapter: "Chapter 40",
    topic: "Immunity",
    question: "Vaccines help the immune system recognize what?",
    options: ["The color blue", "A pathogen or threat", "Magnetic north"],
    answerIndex: 1,
    explanation: "Vaccines train immune memory so the body can respond faster to a real threat.",
  },
];

export function getQuizQuestion(id: number) {
  return quizQuestions.find((question) => question.id === id);
}
