export interface QuizQuestion {
  id: number;
  chapter: string;
  topic: string;
  question: string;
  options: [string, string, string];
  answerIndex: number;
  explanation: string;
}

export const quizQuestions: QuizQuestion[] = [
  {
    id: 1,
    chapter: "Chapter 1",
    topic: "Entropy",
    question: "A gas expands into an evacuated chamber without doing work. Which explanation best captures why the final macrostate is overwhelmingly favored?",
    options: ["Energy is destroyed during free expansion", "There are vastly more microstates compatible with spread-out particles", "Particles acquire a preference for lower pressure regions"],
    answerIndex: 1,
    explanation: "Entropy tracks multiplicity: the dispersed macrostate corresponds to many more microscopic arrangements than the confined one.",
  },
  {
    id: 2,
    chapter: "Chapter 2",
    topic: "Blockchain",
    question: "A transaction has a valid digital signature but later conflicts with an already accepted spend. What does the signature establish, and what does it not establish?",
    options: ["Authorization, but not final inclusion in consensus", "Consensus finality, but not authorization", "The recipient's identity, but not the sender's intent"],
    answerIndex: 0,
    explanation: "A signature proves control of the private key authorized the transaction; consensus rules still decide whether it is accepted.",
  },
  {
    id: 3,
    chapter: "Chapter 3",
    topic: "AI",
    question: "A model performs well on training examples but poorly on held-out cases. Which diagnosis is most precise?",
    options: ["The model has no parameters", "The model has overfit patterns that do not generalize", "The optimizer failed to reduce any loss"],
    answerIndex: 1,
    explanation: "Overfitting means the learned representation matches training data too specifically and fails on new examples.",
  },
  {
    id: 4,
    chapter: "Chapter 4",
    topic: "Physics",
    question: "A skater pushes a wall and moves backward. Which statement avoids the common misunderstanding of Newton's third law?",
    options: ["The wall's force is larger because the skater moves", "The forces are equal and opposite, but act on different bodies", "The action force happens first, then the reaction force appears later"],
    answerIndex: 1,
    explanation: "Third-law force pairs are simultaneous, equal in magnitude, opposite in direction, and act on different objects.",
  },
  {
    id: 5,
    chapter: "Chapter 5",
    topic: "Proofs",
    question: "A proof shows several convincing examples and then states the theorem is true for all cases. What is the main gap?",
    options: ["Examples can suggest a pattern but do not establish universal necessity", "A proof must avoid using definitions", "A theorem is invalid unless it uses symbols"],
    answerIndex: 0,
    explanation: "A proof must show why every admissible case follows, not merely display instances where the claim works.",
  },
  {
    id: 6,
    chapter: "Chapter 6",
    topic: "Memory",
    question: "Why does retrieval practice usually outperform rereading for durable learning?",
    options: ["It forces reconstruction, which strengthens access routes", "It reduces attention by making material feel familiar", "It prevents mistakes from appearing during study"],
    answerIndex: 0,
    explanation: "Retrieval strengthens memory because the learner must actively reconstruct the idea rather than merely recognize it.",
  },
  {
    id: 7,
    chapter: "Chapter 7",
    topic: "Markets",
    question: "Demand for a good rises while supply is relatively inelastic in the short run. What is the most likely immediate effect?",
    options: ["Quantity adjusts fully while price stays fixed", "Price rises more than quantity because supply cannot expand quickly", "Both price and quantity must fall"],
    answerIndex: 1,
    explanation: "When supply is inelastic, a demand increase is absorbed largely through higher prices rather than much higher quantity.",
  },
  {
    id: 8,
    chapter: "Chapter 8",
    topic: "Code",
    question: "A loop terminates correctly only when a condition eventually changes. Which failure is most directly responsible for an infinite loop?",
    options: ["The loop body preserves the truth of its continuation condition", "The program contains more than one variable", "The loop uses a comparison rather than arithmetic"],
    answerIndex: 0,
    explanation: "An infinite loop occurs when execution never reaches a state that makes the continuation condition false.",
  },
  {
    id: 9,
    chapter: "Chapter 9",
    topic: "Probability",
    question: "A fair coin lands heads five times. Which inference is justified before the next flip?",
    options: ["Tails is now due because balance must be restored", "Heads is more likely because a streak has begun", "The conditional probability remains unchanged if flips are independent"],
    answerIndex: 2,
    explanation: "Independence means previous outcomes do not alter the probability distribution of the next fair flip.",
  },
  {
    id: 10,
    chapter: "Chapter 10",
    topic: "Learning",
    question: "An aha moment feels sudden, but what usually makes it cognitively meaningful rather than merely pleasant?",
    options: ["A representation has reorganized so previously separate facts constrain one another", "The learner no longer needs practice or feedback", "The answer has become true because it feels obvious"],
    answerIndex: 0,
    explanation: "Insight matters when the learner's mental model changes, making relationships usable rather than just memorable.",
  },
  {
    id: 11,
    chapter: "Chapter 11",
    topic: "Algebra",
    question: "Solving 3(x - 2) = 2x + 5 depends on which invariant operation?",
    options: ["Changing both sides in the same way preserves the solution set", "Moving terms across equals changes their values permanently", "Parentheses can be removed without distributing coefficients"],
    answerIndex: 0,
    explanation: "Equation solving preserves equivalence by applying valid operations to both sides until the variable is isolated.",
  },
  {
    id: 12,
    chapter: "Chapter 12",
    topic: "Biology",
    question: "Why is DNA suited to storing heritable information rather than merely acting as a structural molecule?",
    options: ["Its sequence can be copied and interpreted through complementary pairing", "Its mass changes whenever a trait is expressed", "It directly folds into every cellular enzyme"],
    answerIndex: 0,
    explanation: "DNA stores information in base sequence, and complementary pairing enables reliable copying and expression.",
  },
  {
    id: 13,
    chapter: "Chapter 13",
    topic: "Philosophy",
    question: "In a Socratic exchange, why is a counterexample more powerful than a request for a definition alone?",
    options: ["It tests whether the definition actually covers the cases it claims to cover", "It replaces reasoning with rhetorical pressure", "It proves that definitions are impossible"],
    answerIndex: 0,
    explanation: "A counterexample exposes a mismatch between a proposed general claim and the cases it is meant to explain.",
  },
  {
    id: 14,
    chapter: "Chapter 14",
    topic: "Optics",
    question: "A prism separates white light into colors. Which mechanism is most responsible?",
    options: ["Different wavelengths refract by different amounts", "The prism emits stored colors when warmed", "Air pressure sorts photons by brightness"],
    answerIndex: 0,
    explanation: "Dispersion occurs because refractive index varies with wavelength, bending colors differently.",
  },
  {
    id: 15,
    chapter: "Chapter 15",
    topic: "Geometry",
    question: "Why does the 180-degree angle sum for triangles depend on the geometry being Euclidean?",
    options: ["Parallel-line behavior determines the angle relationships used in the proof", "Triangles contain three sides by definition", "Measuring angles in degrees forces the sum to be 180"],
    answerIndex: 0,
    explanation: "The standard proof uses Euclidean parallel postulates; curved geometries can have different triangle angle sums.",
  },
  {
    id: 16,
    chapter: "Chapter 16",
    topic: "Evolution",
    question: "Which formulation best avoids the misconception that natural selection aims at perfection?",
    options: ["Traits spread when they improve reproductive success in a given environment", "Organisms evolve traits because they need them", "Selection always produces globally optimal designs"],
    answerIndex: 0,
    explanation: "Natural selection is local and contingent: traits become common when they increase reproductive success under current conditions.",
  },
  {
    id: 17,
    chapter: "Chapter 17",
    topic: "Ethics",
    question: "A policy helps many people slightly but seriously harms a few. Which challenge is most acute for simple utilitarian reasoning?",
    options: ["Whether aggregate benefit can justify concentrated rights violations", "Whether consequences matter at all", "Whether intentions are measurable in kilograms"],
    answerIndex: 0,
    explanation: "Utilitarian aggregation can conflict with concerns about individual rights, distribution, and inviolability.",
  },
  {
    id: 18,
    chapter: "Chapter 18",
    topic: "Gravity",
    question: "Why do astronauts in orbit feel weightless even though Earth's gravity is still acting strongly on them?",
    options: ["They and their spacecraft are in continuous free fall", "Gravity ends at the top of the atmosphere", "Their mass becomes zero during orbital motion"],
    answerIndex: 0,
    explanation: "Orbital weightlessness is free fall: gravity supplies centripetal acceleration while everything falls together.",
  },
  {
    id: 19,
    chapter: "Chapter 19",
    topic: "Fractions",
    question: "Why are 6/8 and 3/4 equivalent, rather than merely close in value?",
    options: ["They represent the same ratio after dividing numerator and denominator by the same nonzero factor", "Both use even denominators", "Their numerators differ by exactly three"],
    answerIndex: 0,
    explanation: "Equivalent fractions preserve the same ratio because scaling both numerator and denominator by the same factor leaves the value unchanged.",
  },
  {
    id: 20,
    chapter: "Chapter 20",
    topic: "Cells",
    question: "Calling mitochondria the cell's powerhouse is incomplete. What is the more precise role?",
    options: ["They convert energy from fuels into ATP through cellular respiration", "They store hereditary information for all traits", "They form the selective boundary around the cell"],
    answerIndex: 0,
    explanation: "Mitochondria help extract energy from molecules and package it in ATP usable by cellular processes.",
  },
  {
    id: 21,
    chapter: "Chapter 21",
    topic: "Logic",
    question: "An argument can be valid even if one premise is false. What does validity actually guarantee?",
    options: ["If the premises were true, the conclusion would have to be true", "The conclusion is psychologically persuasive", "Every premise has been empirically verified"],
    answerIndex: 0,
    explanation: "Validity concerns form: truth of the premises would necessitate truth of the conclusion.",
  },
  {
    id: 22,
    chapter: "Chapter 22",
    topic: "Electricity",
    question: "In a metal wire, what does electric current measure most directly?",
    options: ["Rate of charge flow through a cross-section", "Total number of atoms in the wire", "Speed of electromagnetic information only"],
    answerIndex: 0,
    explanation: "Current is charge per unit time passing through a point or cross-section.",
  },
  {
    id: 23,
    chapter: "Chapter 23",
    topic: "Calculus",
    question: "Why is a derivative at a point not simply the average slope over a visible interval?",
    options: ["It is the limiting slope as the interval around the point shrinks", "It ignores change and records total area", "It only applies to straight lines"],
    answerIndex: 0,
    explanation: "The derivative is an instantaneous rate, defined as a limit of secant slopes.",
  },
  {
    id: 24,
    chapter: "Chapter 24",
    topic: "Ecology",
    question: "Why do producers often sit at the base of ecological energy pyramids?",
    options: ["They transform external energy into biomass available to other organisms", "They consume the largest predators first", "They recycle energy without any loss between levels"],
    answerIndex: 0,
    explanation: "Producers capture energy, often sunlight, and convert it into chemical energy that supports higher trophic levels.",
  },
  {
    id: 25,
    chapter: "Chapter 25",
    topic: "Epistemology",
    question: "Why did Gettier-style cases challenge the simple account of knowledge as justified true belief?",
    options: ["They show that justified true belief can be true partly by luck", "They prove that belief is never involved in knowledge", "They show justification must be mathematical"],
    answerIndex: 0,
    explanation: "Gettier cases suggest that truth plus justification plus belief may still fall short when luck explains the truth.",
  },
  {
    id: 26,
    chapter: "Chapter 26",
    topic: "Relativity",
    question: "In special relativity, why can observers disagree about simultaneity without either being wrong?",
    options: ["Time coordinates depend on inertial frame while physical laws remain invariant", "Light travels instantly between observers", "One observer's clock must be mechanically defective"],
    answerIndex: 0,
    explanation: "Relativity changes the frame-dependent coordinates of events while preserving invariant physical structure.",
  },
  {
    id: 27,
    chapter: "Chapter 27",
    topic: "Statistics",
    question: "A dataset has one extreme outlier. Why might the median describe the center better than the mean?",
    options: ["The median is resistant to extreme values", "The median uses every magnitude more precisely", "The mean cannot be computed when outliers exist"],
    answerIndex: 0,
    explanation: "The median depends on order rather than magnitude, so a single extreme value affects it far less than the mean.",
  },
  {
    id: 28,
    chapter: "Chapter 28",
    topic: "Genetics",
    question: "Why can two siblings inherit different trait combinations from the same parents?",
    options: ["Meiosis and recombination create different combinations of alleles", "Every child receives identical chromosomes from both parents", "Traits are assigned after birth by environment alone"],
    answerIndex: 0,
    explanation: "Independent assortment and recombination shuffle alleles, so siblings need not inherit the same combinations.",
  },
  {
    id: 29,
    chapter: "Chapter 29",
    topic: "Stoicism",
    question: "A Stoic loses status unfairly. Which response best fits the dichotomy of control?",
    options: ["Distinguish the external loss from one's judgment and chosen response", "Deny that social consequences can ever occur", "Treat anger as proof that the loss is morally bad"],
    answerIndex: 0,
    explanation: "Stoicism emphasizes control over judgments and actions, not over external events or others' opinions.",
  },
  {
    id: 30,
    chapter: "Chapter 30",
    topic: "Waves",
    question: "A sound wave passes through air without transporting air molecules from speaker to listener. What is being transmitted?",
    options: ["A pressure disturbance and energy", "Permanent displacement of the entire medium", "A stream of silent particles emitted by the source"],
    answerIndex: 0,
    explanation: "Sound transmits energy through oscillations in pressure; medium particles mostly vibrate around equilibrium positions.",
  },
  {
    id: 31,
    chapter: "Chapter 31",
    topic: "Number Theory",
    question: "Why is 1 excluded from the prime numbers in modern number theory?",
    options: ["Including it would break unique prime factorization", "It has too many positive divisors", "It is not an integer"],
    answerIndex: 0,
    explanation: "Primes are defined to preserve unique factorization; if 1 were prime, factorizations would not be unique.",
  },
  {
    id: 32,
    chapter: "Chapter 32",
    topic: "Photosynthesis",
    question: "What is the conceptual role of light-dependent reactions in photosynthesis?",
    options: ["They convert light energy into chemical carriers used to fix carbon", "They directly assemble glucose without intermediate carriers", "They consume oxygen to release stored ATP"],
    answerIndex: 0,
    explanation: "Light reactions generate ATP and NADPH, which help power carbon fixation in the Calvin cycle.",
  },
  {
    id: 33,
    chapter: "Chapter 33",
    topic: "Metaphysics",
    question: "A ship has every plank replaced over time. What metaphysical issue does the puzzle primarily test?",
    options: ["Persistence of identity through material change", "Whether ships can float in salt water", "Whether names are always arbitrary sounds"],
    answerIndex: 0,
    explanation: "The Ship of Theseus asks what makes an object remain the same object despite replacement of parts.",
  },
  {
    id: 34,
    chapter: "Chapter 34",
    topic: "Thermodynamics",
    question: "Why does heat flow from hot to cold in ordinary conditions?",
    options: ["Energy dispersal toward higher-probability macrostates", "Cold objects actively attract heat as a substance", "Temperature always moves toward the more massive object"],
    answerIndex: 0,
    explanation: "Spontaneous heat flow reflects energy spreading into more probable distributions, consistent with increasing entropy.",
  },
  {
    id: 35,
    chapter: "Chapter 35",
    topic: "Graphs",
    question: "On a distance-time graph, what does a steeper slope represent?",
    options: ["Greater rate of change of distance with respect to time", "Greater total time regardless of distance", "A larger starting position only"],
    answerIndex: 0,
    explanation: "Slope on a distance-time graph represents speed: change in distance divided by change in time.",
  },
  {
    id: 36,
    chapter: "Chapter 36",
    topic: "Neuroscience",
    question: "Why is synaptic transmission not simply an electrical wire carrying current across a gap?",
    options: ["Many synapses convert electrical activity into chemical signaling and back", "Neurons never use electrical gradients", "Synapses require chromosomes to cross between cells"],
    answerIndex: 0,
    explanation: "At many synapses, neurotransmitters carry signals across the synaptic cleft after electrical activity reaches the terminal.",
  },
  {
    id: 37,
    chapter: "Chapter 37",
    topic: "Existentialism",
    question: "Why does existentialist freedom often feel burdensome rather than merely liberating?",
    options: ["Choice makes the agent responsible without a guaranteed script", "Freedom eliminates all consequences", "Authenticity requires rejecting every social relation"],
    answerIndex: 0,
    explanation: "Existentialist freedom carries responsibility because people must choose without hiding behind a fixed essence or script.",
  },
  {
    id: 38,
    chapter: "Chapter 38",
    topic: "Astronomy",
    question: "Why do planets orbit rather than simply fall straight into the Sun?",
    options: ["They have tangential velocity while gravity continually curves their path", "The Sun's gravity turns off at orbital distance", "Planets are pushed outward by empty space"],
    answerIndex: 0,
    explanation: "An orbit combines forward motion with gravitational acceleration toward the central body.",
  },
  {
    id: 39,
    chapter: "Chapter 39",
    topic: "Percentages",
    question: "A price rises by 20% and then falls by 20%. Why is it not back to the original price?",
    options: ["The two percentages use different bases", "Percent decreases are always larger than increases", "Multiplication by percentages is commutative only upward"],
    answerIndex: 0,
    explanation: "The 20% decrease is applied to the increased price, so the bases differ.",
  },
  {
    id: 40,
    chapter: "Chapter 40",
    topic: "Immunity",
    question: "What is the key purpose of vaccination from the immune system's point of view?",
    options: ["Create immune memory without requiring full disease", "Replace all innate immune responses", "Make pathogens evolve more slowly by agreement"],
    answerIndex: 0,
    explanation: "Vaccines expose the immune system to antigens or instructions that build memory before dangerous exposure.",
  },
  {
    id: 41,
    chapter: "Chapter 41",
    topic: "Algebra",
    question: "When solving 2(x + 4) = 3x - 1, what is the most common structural trap?",
    options: ["Failing to distribute before collecting like terms", "Assuming x must be positive", "Treating the equals sign as an instruction to compute left to right"],
    answerIndex: 0,
    explanation: "The coefficient outside parentheses applies to every term inside before terms can be compared.",
  },
  {
    id: 42,
    chapter: "Chapter 42",
    topic: "Cell Biology",
    question: "Why is the cell membrane described as selectively permeable rather than simply a wall?",
    options: ["It regulates passage based on molecular properties and transport mechanisms", "It blocks every molecule equally", "It exists only in plant cells"],
    answerIndex: 0,
    explanation: "Membranes control movement through lipid structure, channels, pumps, and gradients rather than acting as solid walls.",
  },
  {
    id: 43,
    chapter: "Chapter 43",
    topic: "Philosophy",
    question: "What distinguishes an empirical claim from a purely conceptual claim?",
    options: ["It is answerable by observation or experience", "It cannot be wrong by definition", "It concerns values rather than facts"],
    answerIndex: 0,
    explanation: "Empirical claims are tested against the world through observation, measurement, or experience.",
  },
  {
    id: 44,
    chapter: "Chapter 44",
    topic: "Motion",
    question: "Two runners cover the same distance, but one takes less time. Which quantity differs, and why?",
    options: ["Average speed, because distance is divided by elapsed time", "Mass, because faster objects must weigh less", "Displacement, because time changes direction"],
    answerIndex: 0,
    explanation: "Average speed compares distance traveled to elapsed time; less time for the same distance means greater speed.",
  },
  {
    id: 45,
    chapter: "Chapter 45",
    topic: "Geometry",
    question: "Why does rectangle area use multiplication rather than addition of side lengths?",
    options: ["It counts a two-dimensional array of unit squares", "It measures boundary distance around the shape", "It only applies when all sides are equal"],
    answerIndex: 0,
    explanation: "Area measures coverage in two dimensions, so length and width combine as rows times columns of units.",
  },
  {
    id: 46,
    chapter: "Chapter 46",
    topic: "Ecology",
    question: "An organism's niche is broader than its physical location because it includes what?",
    options: ["Its functional role, resource use, and interactions", "Only the coordinates where it sleeps", "Its taxonomic name in Latin"],
    answerIndex: 0,
    explanation: "A niche describes how an organism lives in an ecosystem, including resources, conditions, and relationships.",
  },
  {
    id: 47,
    chapter: "Chapter 47",
    topic: "Ethics",
    question: "Why are moral dilemmas philosophically interesting rather than just emotionally difficult?",
    options: ["They expose conflicts between principles that each seem independently compelling", "They prove that moral reasoning is impossible", "They occur only when no one has preferences"],
    answerIndex: 0,
    explanation: "Dilemmas matter because plausible values or duties can pull in incompatible directions.",
  },
  {
    id: 48,
    chapter: "Chapter 48",
    topic: "Energy",
    question: "Why does kinetic energy scale with velocity squared rather than velocity alone?",
    options: ["The work needed to accelerate an object accumulates with changing velocity", "Velocity is not part of kinetic energy", "Only mass determines energy of motion"],
    answerIndex: 0,
    explanation: "The work-energy relationship yields kinetic energy proportional to mass times velocity squared.",
  },
  {
    id: 49,
    chapter: "Chapter 49",
    topic: "Probability",
    question: "What does assigning probability 1 to an event mean within a model?",
    options: ["The event is certain under that model's assumptions", "The event has already happened in history", "The event is morally necessary"],
    answerIndex: 0,
    explanation: "Probability 1 expresses certainty relative to the probability model, not necessarily metaphysical necessity.",
  },
  {
    id: 50,
    chapter: "Chapter 50",
    topic: "Calculus",
    question: "If position is a function of time, why is velocity its derivative rather than its total change?",
    options: ["Velocity measures instantaneous rate of change with respect to time", "Velocity measures the area under the position curve", "Velocity ignores the time variable entirely"],
    answerIndex: 0,
    explanation: "Velocity is how position changes per unit time at an instant, which is captured by the derivative.",
  },
  {
    id: 51,
    chapter: "Chapter 51",
    topic: "Genetics",
    question: "For a simple recessive trait, why can two unaffected carriers have an affected child?",
    options: ["The child can inherit the recessive allele from both parents", "Carrier parents cannot pass recessive alleles", "Dominant alleles become recessive after fertilization"],
    answerIndex: 0,
    explanation: "If each parent contributes a recessive allele, the child can express the recessive phenotype.",
  },
  {
    id: 52,
    chapter: "Chapter 52",
    topic: "Epistemology",
    question: "Why is justification not the same thing as psychological certainty?",
    options: ["Justification concerns reasons or evidence, not merely confidence", "Certainty always proves truth", "Justification requires never revising beliefs"],
    answerIndex: 0,
    explanation: "A person can feel certain without adequate reasons, and can be justified while still aware of fallibility.",
  },
  {
    id: 53,
    chapter: "Chapter 53",
    topic: "Thermodynamics",
    question: "The first law of thermodynamics is best understood as a constraint on what?",
    options: ["Accounting for energy as it transfers or changes form", "Guaranteeing that every process is reversible", "Preventing entropy from increasing"],
    answerIndex: 0,
    explanation: "The first law says energy is conserved: it can move or transform, but the total accounting must balance.",
  },
  {
    id: 54,
    chapter: "Chapter 54",
    topic: "Linear Algebra",
    question: "What makes a vector more than just a list of numbers in linear algebra?",
    options: ["It is an element that can be scaled and added within a vector space", "It must always be drawn as an arrow in physical space", "It cannot represent abstract quantities"],
    answerIndex: 0,
    explanation: "Vectors are defined by their role in vector spaces, where addition and scalar multiplication obey specific rules.",
  },
  {
    id: 55,
    chapter: "Chapter 55",
    topic: "Evolution",
    question: "Why is genetic drift especially powerful in small populations?",
    options: ["Random sampling error has a larger effect on allele frequencies", "Selection stops operating in small groups", "Mutations become intentional when populations shrink"],
    answerIndex: 0,
    explanation: "In small populations, chance events can substantially shift allele frequencies from one generation to the next.",
  },
  {
    id: 56,
    chapter: "Chapter 56",
    topic: "Logic",
    question: "Why does a contradiction create trouble in classical logic?",
    options: ["From inconsistent premises, arbitrary conclusions can be derived", "It makes every statement empirically false", "It only affects arguments written in symbols"],
    answerIndex: 0,
    explanation: "Classical logic treats contradictions as explosive: inconsistency undermines meaningful constraint on conclusions.",
  },
  {
    id: 57,
    chapter: "Chapter 57",
    topic: "Quantum Physics",
    question: "What does superposition mean before measurement in standard quantum mechanics?",
    options: ["The state is represented as a combination of possible measurement outcomes", "The particle secretly chooses one outcome but hides it from mathematics", "The object becomes physically larger than the apparatus"],
    answerIndex: 0,
    explanation: "A superposed state is mathematically expressed as a combination of basis states associated with possible outcomes.",
  },
  {
    id: 58,
    chapter: "Chapter 58",
    topic: "Number Theory",
    question: "Why does saying two integers are coprime make a stronger claim than saying neither is prime?",
    options: ["It specifies that their greatest common divisor is 1", "It means both numbers must be odd", "It means their product is prime"],
    answerIndex: 0,
    explanation: "Coprimality is a relation between numbers: they share no positive factor greater than 1.",
  },
  {
    id: 59,
    chapter: "Chapter 59",
    topic: "Physiology",
    question: "Why is homeostasis better described as dynamic regulation than as staying unchanged?",
    options: ["Internal variables are continually adjusted around viable ranges", "Organisms stop exchanging matter with the environment", "All internal conditions remain exactly constant"],
    answerIndex: 0,
    explanation: "Homeostasis involves feedback mechanisms that maintain variables within ranges despite changing conditions.",
  },
  {
    id: 60,
    chapter: "Chapter 60",
    topic: "Philosophy of Mind",
    question: "What is the central burden for mind-body dualism?",
    options: ["Explaining interaction between mental and physical substances or properties", "Showing that bodies occupy space", "Denying that conscious experience exists"],
    answerIndex: 0,
    explanation: "Dualism must explain how mental reality relates causally or systematically to physical processes.",
  },
  {
    id: 61,
    chapter: "Chapter 61",
    topic: "Relativity",
    question: "Why is the constancy of light speed surprising in special relativity?",
    options: ["It holds for all inertial observers despite their relative motion", "It depends on the color of the observer's clock", "It means light has infinite speed"],
    answerIndex: 0,
    explanation: "Special relativity begins from the invariant speed of light for all inertial frames, unlike ordinary velocity addition.",
  },
  {
    id: 62,
    chapter: "Chapter 62",
    topic: "Functions",
    question: "What makes a relation a function rather than just a set of ordered pairs?",
    options: ["Each input is associated with exactly one output", "Every output must be larger than its input", "The graph must be a straight line"],
    answerIndex: 0,
    explanation: "A function assigns a unique output to each input in its domain.",
  },
  {
    id: 63,
    chapter: "Chapter 63",
    topic: "Molecular Biology",
    question: "Why is transcription not the same process as translation?",
    options: ["Transcription copies DNA information into RNA; translation uses RNA to build protein", "Transcription builds proteins directly from amino acids", "Translation copies RNA back into DNA in all cells"],
    answerIndex: 0,
    explanation: "Transcription produces RNA from DNA; translation reads RNA codons to assemble a polypeptide.",
  },
  {
    id: 64,
    chapter: "Chapter 64",
    topic: "Ethics",
    question: "What does deontology preserve that pure outcome-based reasoning may threaten?",
    options: ["Constraints from duties, rights, or principles", "The claim that consequences never matter", "The idea that moral rules are statistical averages"],
    answerIndex: 0,
    explanation: "Deontological theories often treat some actions as required or forbidden regardless of aggregate consequences.",
  },
  {
    id: 65,
    chapter: "Chapter 65",
    topic: "Electromagnetism",
    question: "What is the key condition for electromagnetic induction in a circuit?",
    options: ["A changing magnetic flux through the circuit", "A static charge placed far from any conductor", "A constant temperature gradient alone"],
    answerIndex: 0,
    explanation: "Faraday's law links induced electromotive force to changing magnetic flux.",
  },
  {
    id: 66,
    chapter: "Chapter 66",
    topic: "Probability",
    question: "If A and B are independent, what remains unchanged when you learn B occurred?",
    options: ["The probability assigned to A", "The sample space's existence", "The fact that A and B are mutually exclusive"],
    answerIndex: 0,
    explanation: "Independence means P(A | B) = P(A), so B provides no probabilistic information about A.",
  },
  {
    id: 67,
    chapter: "Chapter 67",
    topic: "Ecology",
    question: "Why can removing a keystone species change an ecosystem disproportionately?",
    options: ["Its interactions stabilize or structure many other relationships", "It is always the most numerous species", "It contains more energy than all producers combined"],
    answerIndex: 0,
    explanation: "Keystone species have effects on community structure that are large relative to their abundance.",
  },
  {
    id: 68,
    chapter: "Chapter 68",
    topic: "Metaphysics",
    question: "What does the problem of personal identity ask us to specify?",
    options: ["The criterion by which a person remains the same through change", "The legal spelling of a person's name", "The biological fact that bodies age"],
    answerIndex: 0,
    explanation: "Personal identity theories try to explain persistence of the same person across psychological and bodily change.",
  },
  {
    id: 69,
    chapter: "Chapter 69",
    topic: "Mechanics",
    question: "Why is momentum conserved in an isolated collision even when kinetic energy is not?",
    options: ["Internal forces cancel in pairs while energy may transform into other forms", "Objects stop having mass during impact", "Momentum conservation requires perfectly elastic collisions"],
    answerIndex: 0,
    explanation: "Total momentum is conserved in isolated systems; kinetic energy can become heat, sound, or deformation.",
  },
  {
    id: 70,
    chapter: "Chapter 70",
    topic: "Geometry",
    question: "Why is the hypotenuse necessarily the longest side of a right triangle?",
    options: ["It lies opposite the largest angle", "It is always drawn horizontally", "It is defined as the side with the smallest measure"],
    answerIndex: 0,
    explanation: "In a triangle, larger angles face longer sides; the right angle is the largest angle in a right triangle.",
  },
  {
    id: 71,
    chapter: "Chapter 71",
    topic: "Immunology",
    question: "Why does antibody specificity matter for immune defense?",
    options: ["It lets immune responses target molecular features associated with threats", "It prevents antibodies from binding any molecule", "It makes antibodies identical to pathogens"],
    answerIndex: 0,
    explanation: "Antibodies bind particular antigens, enabling targeted recognition and response.",
  },
  {
    id: 72,
    chapter: "Chapter 72",
    topic: "Political Philosophy",
    question: "What problem is social contract theory primarily trying to solve?",
    options: ["How political authority can be legitimate over free and equal persons", "How rulers can avoid all obligations", "Why natural science requires elections"],
    answerIndex: 0,
    explanation: "Social contract theories explain legitimate political order through consent, agreement, or hypothetical justification.",
  },
  {
    id: 73,
    chapter: "Chapter 73",
    topic: "Astrophysics",
    question: "Why is the event horizon of a black hole not simply a material surface?",
    options: ["It is a causal boundary beyond which escape paths do not reach outside observers", "It is a solid shell made of compressed light", "It is the place where gravity becomes exactly zero"],
    answerIndex: 0,
    explanation: "The event horizon marks a boundary in spacetime's causal structure, not a physical crust.",
  },
  {
    id: 74,
    chapter: "Chapter 74",
    topic: "Logarithms",
    question: "Why does log_b(xy) split into log_b(x) + log_b(y)?",
    options: ["Multiplying powers with the same base adds exponents", "Logarithms turn every operation into subtraction", "The rule holds only because x and y are integers"],
    answerIndex: 0,
    explanation: "Logarithms are exponents; products of same-base powers correspond to sums of exponents.",
  },
  {
    id: 75,
    chapter: "Chapter 75",
    topic: "Biochemistry",
    question: "How does an enzyme speed a reaction without changing the reaction's overall free energy difference?",
    options: ["It lowers the activation-energy barrier", "It makes products contain no energy", "It changes atoms into different elements"],
    answerIndex: 0,
    explanation: "Enzymes stabilize transition states and lower activation energy, but they do not change overall thermodynamic favorability.",
  },
  {
    id: 76,
    chapter: "Chapter 76",
    topic: "Aesthetics",
    question: "Why is aesthetic judgment philosophically difficult?",
    options: ["It seems subjective yet often asks for shared reasons", "It is entirely reducible to measuring brightness", "It never involves perception or interpretation"],
    answerIndex: 0,
    explanation: "Aesthetic judgments feel personal but are commonly defended with reasons intended to be intelligible to others.",
  },
  {
    id: 77,
    chapter: "Chapter 77",
    topic: "Waves",
    question: "If wave speed stays constant, what happens to wavelength when frequency increases?",
    options: ["Wavelength decreases", "Wavelength increases proportionally", "Amplitude must become zero"],
    answerIndex: 0,
    explanation: "The relationship v = f lambda means wavelength decreases when frequency increases at constant wave speed.",
  },
  {
    id: 78,
    chapter: "Chapter 78",
    topic: "Statistics",
    question: "Why can a zero correlation fail to prove that two variables are unrelated?",
    options: ["Correlation measures linear association and can miss nonlinear structure", "Correlation is only defined for moral claims", "Zero correlation means the data were not collected"],
    answerIndex: 0,
    explanation: "A correlation coefficient of zero rules out linear association, not every possible dependence pattern.",
  },
  {
    id: 79,
    chapter: "Chapter 79",
    topic: "Evolution",
    question: "What makes convergent evolution evidence for similar selective pressures rather than close ancestry?",
    options: ["Similar traits arise independently in distant lineages", "All similar traits must come from one ancestor", "Unrelated species cannot face similar environments"],
    answerIndex: 0,
    explanation: "Convergence occurs when different lineages independently evolve similar adaptations under similar constraints.",
  },
  {
    id: 80,
    chapter: "Chapter 80",
    topic: "Existentialism",
    question: "In Sartre's phrase 'existence precedes essence,' what is being denied?",
    options: ["That humans are born with a fixed nature that determines their choices", "That humans have bodies", "That choices can have consequences"],
    answerIndex: 0,
    explanation: "Sartre rejects the idea of a predetermined human essence; people define themselves through action.",
  },
  {
    id: 81,
    chapter: "Chapter 81",
    topic: "Optics",
    question: "A ray bends toward the normal entering a denser medium. Which causal explanation is most precise?",
    options: ["Its wavefront changes speed across the boundary", "Its frequency increases because the medium is darker", "Its photons acquire more rest mass"],
    answerIndex: 0,
    explanation: "Refraction occurs because light's speed changes in a medium while frequency remains continuous across the boundary.",
  },
  {
    id: 82,
    chapter: "Chapter 82",
    topic: "Sequences",
    question: "How can you distinguish a geometric sequence from an arithmetic one when values are not obvious?",
    options: ["Check whether consecutive ratios are constant", "Check whether consecutive differences alternate signs", "Check whether every term is prime"],
    answerIndex: 0,
    explanation: "Geometric sequences multiply by a fixed common ratio; arithmetic sequences add a fixed difference.",
  },
  {
    id: 83,
    chapter: "Chapter 83",
    topic: "Neuroscience",
    question: "Why is a synapse better understood as an interface than as a simple gap?",
    options: ["It transforms, regulates, and passes signals between cells", "It prevents neurons from affecting each other", "It stores genetic instructions for neurons"],
    answerIndex: 0,
    explanation: "Synapses are specialized junctions where signals are transmitted and modulated.",
  },
  {
    id: 84,
    chapter: "Chapter 84",
    topic: "Virtue Ethics",
    question: "What does virtue ethics ask that rule- or consequence-focused theories may underemphasize?",
    options: ["What kind of person one becomes through habits and judgment", "How to calculate every outcome exactly", "Whether all duties can be ignored"],
    answerIndex: 0,
    explanation: "Virtue ethics centers character, practical wisdom, and habituated dispositions toward good action.",
  },
  {
    id: 85,
    chapter: "Chapter 85",
    topic: "Electric Circuits",
    question: "In Ohm's law, what would make current decrease if voltage stays fixed?",
    options: ["Increasing resistance", "Increasing voltage by the same amount", "Removing all conductive paths while keeping current unchanged"],
    answerIndex: 0,
    explanation: "From I = V/R, current falls as resistance rises when voltage is constant.",
  },
  {
    id: 86,
    chapter: "Chapter 86",
    topic: "Topology",
    question: "Why are a coffee mug and a torus often treated as equivalent in topology?",
    options: ["Each has one hole under continuous deformation", "They have the same volume", "They are made from the same material"],
    answerIndex: 0,
    explanation: "Topology studies properties preserved by continuous deformation, such as number of holes.",
  },
  {
    id: 87,
    chapter: "Chapter 87",
    topic: "Microbiology",
    question: "What structural feature most sharply distinguishes prokaryotic bacteria from eukaryotic cells?",
    options: ["Absence of a membrane-bound nucleus", "Presence of DNA in every case", "Ability to exchange energy with the environment"],
    answerIndex: 0,
    explanation: "Bacteria are prokaryotes because their genetic material is not enclosed in a membrane-bound nucleus.",
  },
  {
    id: 88,
    chapter: "Chapter 88",
    topic: "Philosophy of Science",
    question: "Why did Popper emphasize falsifiability rather than confirmation alone?",
    options: ["Bold theories should risk being shown false by possible observations", "Scientific claims must never make predictions", "A claim is scientific only if it has already been proven final"],
    answerIndex: 0,
    explanation: "Falsifiability requires that a theory rule out some possible observations, making it testable in a risky way.",
  },
  {
    id: 89,
    chapter: "Chapter 89",
    topic: "Fluids",
    question: "Why does buoyant force depend on displaced fluid rather than the object's color or composition alone?",
    options: ["Pressure differences over the submerged surface create an upward net force", "Fluid pushes only on objects made of metal", "Gravity stops acting when objects enter liquid"],
    answerIndex: 0,
    explanation: "Buoyancy comes from pressure increasing with depth, creating a net upward force equal to displaced fluid weight.",
  },
  {
    id: 90,
    chapter: "Chapter 90",
    topic: "Set Theory",
    question: "What distinguishes intersection from union in set theory?",
    options: ["Intersection requires membership in both sets; union allows membership in either", "Intersection contains only numbers, union contains words", "Union always has fewer elements than intersection"],
    answerIndex: 0,
    explanation: "Intersection is shared membership; union combines all elements that appear in at least one set.",
  },
  {
    id: 91,
    chapter: "Chapter 91",
    topic: "Anatomy",
    question: "Why are red blood cells specialized for oxygen transport rather than general cellular control?",
    options: ["They are packed with hemoglobin and lack many organelles in maturity", "They contain more nuclei than other body cells", "They digest pathogens through synaptic signaling"],
    answerIndex: 0,
    explanation: "Mature red blood cells are structured to maximize hemoglobin-mediated oxygen transport.",
  },
  {
    id: 92,
    chapter: "Chapter 92",
    topic: "Moral Philosophy",
    question: "Why does the trolley problem remain useful even though it is artificial?",
    options: ["It isolates tensions between consequences, duties, and agency", "It proves all real moral choices are identical to train cases", "It removes the need for moral theory"],
    answerIndex: 0,
    explanation: "Thought experiments simplify context to reveal competing moral intuitions and principles.",
  },
  {
    id: 93,
    chapter: "Chapter 93",
    topic: "Cosmology",
    question: "Why does redshift support cosmic expansion rather than merely proving galaxies are red objects?",
    options: ["Spectral lines are shifted toward longer wavelengths in a systematic pattern", "All distant galaxies emit only red light", "Red paint absorbs cosmic background radiation"],
    answerIndex: 0,
    explanation: "Redshift is measured by displaced spectral lines, indicating stretching of wavelength associated with recession and expansion.",
  },
  {
    id: 94,
    chapter: "Chapter 94",
    topic: "Differential Equations",
    question: "What makes a differential equation a model of change rather than just an algebraic constraint?",
    options: ["It relates quantities to their rates of change", "It forbids functions from having variables", "It only accepts whole-number solutions"],
    answerIndex: 0,
    explanation: "Differential equations describe how a state evolves by involving derivatives.",
  },
  {
    id: 95,
    chapter: "Chapter 95",
    topic: "Genomics",
    question: "Why can a DNA mutation have no visible phenotypic effect?",
    options: ["The change may be silent, noncoding, repaired, or buffered by biology", "Every mutation necessarily changes every trait", "Mutations occur only outside genomes"],
    answerIndex: 0,
    explanation: "Many mutations do not alter proteins or traits because of redundancy, location, repair, or regulatory context.",
  },
  {
    id: 96,
    chapter: "Chapter 96",
    topic: "Phenomenology",
    question: "What is phenomenology trying to examine when it brackets assumptions about the external world?",
    options: ["How experience appears from the first-person perspective", "Whether atoms have moral status", "How to replace perception with statistics"],
    answerIndex: 0,
    explanation: "Phenomenology studies structures of lived experience and appearance, often by suspending certain metaphysical assumptions.",
  },
  {
    id: 97,
    chapter: "Chapter 97",
    topic: "Nuclear Physics",
    question: "Why can nuclear fission release energy even though splitting a nucleus sounds like it should require energy?",
    options: ["Products can have greater binding energy per nucleon, releasing the difference", "Mass is created from nothing during the split", "Electrons become heavier than protons"],
    answerIndex: 0,
    explanation: "Fission releases energy when the final nuclei are more tightly bound overall, converting mass-energy difference into released energy.",
  },
  {
    id: 98,
    chapter: "Chapter 98",
    topic: "Trigonometry",
    question: "Why does sine in a right triangle depend on the chosen angle rather than the triangle alone?",
    options: ["Opposite and adjacent sides are defined relative to the selected angle", "The hypotenuse changes length when named", "Sine is independent of all side ratios"],
    answerIndex: 0,
    explanation: "For a chosen acute angle, sine is opposite over hypotenuse; changing the reference angle changes which side is opposite.",
  },
  {
    id: 99,
    chapter: "Chapter 99",
    topic: "Biology",
    question: "What is the evolutionary purpose of meiosis producing haploid gametes?",
    options: ["Fertilization can restore diploid chromosome number while mixing variation", "Gametes need twice as many chromosomes as body cells", "It prevents any genetic variation between generations"],
    answerIndex: 0,
    explanation: "Meiosis halves chromosome number so fertilization restores diploidy and creates new allele combinations.",
  },
  {
    id: 100,
    chapter: "Chapter 100",
    topic: "Philosophy",
    question: "What is the force of Hume's is-ought problem?",
    options: ["Descriptive premises alone do not logically entail normative conclusions", "Moral claims can never be discussed rationally", "Facts and values are always identical categories"],
    answerIndex: 0,
    explanation: "The is-ought gap warns that a conclusion about what ought to be requires some normative bridge, not facts alone.",
  },
];

export function getQuizQuestion(id: number) {
  return quizQuestions.find((question) => question.id === id);
}
