import {
  buildModelDoc,
  createTimeToolActions,
  type EvidenceApiDemoDefinition,
  STANDARD_CATEGORY_ORDER,
} from "../demo-definition";
import type { SimulationAction } from "../types";

const EVAL_DEFINITION = `Verify that trial users learned FlowStack well enough to activate and convert across a multidimensional onboarding surface:
- workspace setup and profile completion (optional paths: guided tour vs self-serve),
- integrations (Slack, GitHub, Jira) with correct scopes and recovery from misconfiguration,
- project creation (template vs blank, automations, cross-functional workflows),
- team collaboration (invites, permissions, delegation, wrong-workspace mistakes),
- activation milestones (checklist, collaborative edits, usage thresholds),
- support touchpoints (help center, live onboarding) and re-engagement after idle gaps.

Evidence should capture non-linear tool events, idle gaps, learner reflections, errors recovered, branching decisions, and outcomes tied to learning-to-conversion.`;

const FLOWSTACK_ACTIONS: SimulationAction[] = [
  {
    id: "start_trial",
    label: "Start trial",
    description: "Create workspace and accept trial terms.",
    category: "onboarding",
    blockHint: "Trial workspace setup",
    cta: "Start trial",
    kind: "evidence",
    dimension: "workspace_setup",
    outcome: "success",
  },
  {
    id: "complete_profile",
    label: "Complete profile",
    description: "Fill role, team size, and use-case fields.",
    category: "onboarding",
    blockHint: "Profile completion",
    cta: "Save profile",
    kind: "evidence",
    dimension: "workspace_setup",
    outcome: "success",
  },
  {
    id: "skip_product_tour",
    label: "Skip product tour",
    description: "Dismiss guided tour and explore self-serve.",
    category: "onboarding",
    blockHint: "Self-serve exploration",
    cta: "Skip tour",
    kind: "evidence",
    dimension: "self_serve_navigation",
    outcome: "partial",
  },
  {
    id: "connect_slack",
    label: "Connect Slack",
    description: "OAuth Slack with correct workspace channel.",
    category: "integrations",
    blockHint: "Slack integration",
    cta: "Connect Slack",
    kind: "evidence",
    dimension: "integration_connect",
    outcome: "success",
  },
  {
    id: "connect_github",
    label: "Connect GitHub",
    description: "Link repo for issue sync and PR notifications.",
    category: "integrations",
    blockHint: "GitHub integration",
    cta: "Connect GitHub",
    kind: "evidence",
    dimension: "integration_connect",
    outcome: "success",
  },
  {
    id: "misconfigure_slack_scope",
    label: "Misconfigure Slack scope",
    description: "Grant overly narrow channel scope, then notice missing events.",
    category: "integrations",
    blockHint: "Integration troubleshooting",
    cta: "Save wrong scope",
    kind: "evidence",
    repeatable: true,
    dimension: "integration_recovery",
    outcome: "struggle",
  },
  {
    id: "fix_slack_scope",
    label: "Fix Slack scope",
    description: "Re-authorize with correct channel and verify events flow.",
    category: "integrations",
    blockHint: "Integration recovery",
    cta: "Re-authorize Slack",
    kind: "evidence",
    suggestedAfter: ["misconfigure_slack_scope"],
    dimension: "integration_recovery",
    outcome: "success",
  },
  {
    id: "create_project_template",
    label: "Create from template",
    description: "Spin up Team Onboarding template project.",
    category: "projects",
    blockHint: "Template project",
    cta: "Use template",
    kind: "evidence",
    dimension: "project_setup",
    outcome: "success",
  },
  {
    id: "create_blank_project",
    label: "Create blank project",
    description: "Start empty project and configure columns manually.",
    category: "projects",
    blockHint: "Blank project setup",
    cta: "Create blank",
    kind: "evidence",
    dimension: "project_setup",
    outcome: "partial",
  },
  {
    id: "configure_automation",
    label: "Add automation rule",
    description: "Create when-status-changes → notify Slack rule.",
    category: "projects",
    blockHint: "Workflow automation",
    cta: "Save automation",
    kind: "evidence",
    dimension: "workflow_design",
    outcome: "success",
  },
  {
    id: "invite_editor",
    label: "Invite editor",
    description: "Invite colleague with editor permissions.",
    category: "team",
    blockHint: "Team invite",
    cta: "Send invite",
    kind: "evidence",
    dimension: "team_collaboration",
    outcome: "success",
  },
  {
    id: "invite_viewer",
    label: "Invite viewer only",
    description: "Invite stakeholder with read-only access.",
    category: "team",
    blockHint: "Permissions",
    cta: "Invite viewer",
    kind: "evidence",
    dimension: "permissions",
    outcome: "success",
  },
  {
    id: "delegate_project_admin",
    label: "Delegate project admin",
    description: "Transfer project ownership to teammate.",
    category: "team",
    blockHint: "Delegation",
    cta: "Delegate admin",
    kind: "evidence",
    dimension: "permissions",
    outcome: "partial",
  },
  {
    id: "complete_activation_checklist",
    label: "Complete activation checklist",
    description: "Finish in-app activation checklist items.",
    category: "activation",
    blockHint: "Activation milestone",
    cta: "Complete checklist",
    kind: "evidence",
    dimension: "activation",
    outcome: "success",
  },
  {
    id: "first_collaborative_edit",
    label: "First collaborative edit",
    description: "Two users edit same task concurrently.",
    category: "activation",
    blockHint: "Collaboration milestone",
    cta: "Co-edit task",
    kind: "evidence",
    dimension: "collaboration",
    outcome: "success",
  },
  {
    id: "view_upgrade_path",
    label: "View upgrade path",
    description: "Open pricing modal after hitting trial limits.",
    category: "activation",
    blockHint: "Conversion signal",
    cta: "View pricing",
    kind: "evidence",
    dimension: "conversion_intent",
    outcome: "partial",
  },
  {
    id: "open_help_center",
    label: "Open help center",
    description: "Search docs for integration troubleshooting.",
    category: "support",
    blockHint: "Self-serve support",
    cta: "Open help",
    kind: "evidence",
    repeatable: true,
    dimension: "support_usage",
    outcome: "partial",
  },
  {
    id: "attend_live_onboarding",
    label: "Join live onboarding",
    description: "Attend CS-led onboarding webinar.",
    category: "support",
    blockHint: "Live onboarding",
    cta: "Join session",
    kind: "evidence",
    dimension: "guided_learning",
    outcome: "success",
  },
  {
    id: "abandon_mid_flow",
    label: "Abandon mid-flow",
    description: "Close tab during Slack OAuth without finishing.",
    category: "edge_cases",
    blockHint: "Drop-off",
    cta: "Abandon flow",
    kind: "evidence",
    repeatable: true,
    dimension: "drop_off",
    outcome: "failure",
  },
  {
    id: "wrong_workspace_invite",
    label: "Wrong-workspace invite",
    description: "Send invite to personal email outside company domain.",
    category: "edge_cases",
    blockHint: "Invite mistake",
    cta: "Send wrong invite",
    kind: "evidence",
    dimension: "mistake_recovery",
    outcome: "struggle",
  },
  {
    id: "return_after_idle",
    label: "Return after idle gap",
    description: "Resume onboarding after an idle period.",
    category: "edge_cases",
    blockHint: "Re-engagement",
    cta: "Resume session",
    kind: "evidence",
    repeatable: true,
    dimension: "re_engagement",
    outcome: "partial",
  },
  ...createTimeToolActions(),
];

export const flowstackDemo: EvidenceApiDemoDefinition = {
  id: "flowstack",
  productName: "FlowStack",
  integrationName: "flowstack-onboarding-agent",
  useCase: "Trial onboarding & activation",
  tagline: "Team collaboration platform",
  saasCategory: "Project management",
  description:
    "The classic SaaS trial scenario — branch across onboarding, integrations, projects, and team invites until activation.",
  scenarioTitle: "Non-linear trial onboarding",
  scenarioIntro:
    "Learners progress through a **non-linear product trial** — branching across setup paths, integrations, projects, team permissions, and activation milestones in any order.",
  workspaceDescription: "FlowStack trial-to-activation learning verification",
  initials: "FS",
  accent: "indigo",
  evalDefinition: EVAL_DEFINITION,
  workspacePrompt: `SaaS product onboarding verification for FlowStack, a team collaboration platform.
Trial users may take non-linear paths: skip tours, connect integrations in any order, invite teammates before or after project setup, hit friction, abandon and return days later.
Verify learning-to-conversion across integrations, projects, team permissions, activation, and support — not a single linear checklist.
Create assessable blocks for each competency dimension (setup, integrations, projects, team, activation, support/re-engagement).`,
  modelDocFilename: "flowstack-eval-model.md",
  modelDoc: buildModelDoc(
    {
      productName: "FlowStack",
      integrationName: "flowstack-onboarding-agent",
      evalDefinition: EVAL_DEFINITION,
      modelDocFilename: "flowstack-eval-model.md",
      useCase: "Trial onboarding & activation",
      scenarioIntro:
        "Learners progress through a **non-linear product trial** — branching across setup paths, integrations, projects, team permissions, and activation milestones in any order.",
    },
    `| workspace_setup | Trial start, profile completion, self-serve navigation |
| integration_connect | Slack, GitHub, Jira OAuth and scope correctness |
| integration_recovery | Detecting and fixing misconfigured scopes |
| project_setup | Template vs blank project creation |
| workflow_design | Automation rules and cross-tool workflows |
| team_collaboration | Invites, roles, delegation |
| activation | Checklist completion, collaborative edits, upgrade signals |
| support_usage | Help center and live onboarding touchpoints |
| re_engagement | Return after idle gaps |
| mistake_recovery | Wrong-workspace invites, abandon flows |`
  ),
  toolName: "flowstack",
  simulatorToolName: "flowstack_events",
  schemaVersion: "flowstack_evidence_v2",
  evidenceGoals: ["trial_activation", "integration_connect", "team_invite", "multidimensional_onboarding"],
  integrationHints: {
    event_verbs: ["time_gap_elapsed", "connect_slack", "invite_editor"],
    goals: ["trial_activation", "multidimensional_onboarding"],
  },
  partnerDescription:
    "FlowStack partner integration that emits trial product events and uploads evidence to OpenLesson.",
  integrationSkillContext: "FlowStack trial onboarding integration with branching product events",
  categoryMeta: {
    onboarding: {
      label: "Onboarding paths",
      description: "Trial start, profile, tour — users rarely follow one sequence.",
    },
    integrations: {
      label: "Integrations",
      description: "Connect, misconfigure, and recover across Slack, GitHub, and Jira.",
    },
    projects: {
      label: "Projects & workflows",
      description: "Templates, blank projects, and automation rules.",
    },
    team: {
      label: "Team & permissions",
      description: "Invites, roles, and delegation — often parallel to project setup.",
    },
    activation: {
      label: "Activation",
      description: "Checklists, collaborative milestones, and upgrade signals.",
    },
    support: {
      label: "Support & learning",
      description: "Help center and live onboarding touchpoints.",
    },
    edge_cases: {
      label: "Friction & return paths",
      description: "Abandonment, mistakes, and re-engagement after gaps.",
    },
    simulation_tools: {
      label: "Calendar gaps",
      description: "Record idle time between sessions when calendar gaps matter.",
    },
  },
  categoryOrder: STANDARD_CATEGORY_ORDER,
  actions: FLOWSTACK_ACTIONS,
};