import {
  buildModelDoc,
  createTimeToolActions,
  type EvidenceApiDemoDefinition,
  STANDARD_CATEGORY_ORDER,
} from "../demo-definition";
import type { SimulationAction } from "../types";

const USE_CASE = "Escalation handling certification";
const SCENARIO_INTRO =
  "Support agents complete an **escalation handling certification program** — branching across intake, channel context, playbook execution, supervisor handoffs, SLA pressure, and QA evaluation. Real queues are rarely linear.";

const EVAL_DEFINITION = `Verify that support agents can pass escalation-handling certification on HelpHive across a non-linear live-queue surface:
- program enrollment, rubric acceptance, and training posture (guided vs experienced),
- channel context (Slack escalation, Zendesk history, priority routing) with misroute recovery,
- playbook execution (de-escalation macros, escalation trees, root-cause documentation),
- supervision chain (lead escalation, manager shadow, specialist handoff),
- certification milestones (in-SLA resolution, QA pass, team-lead program interest),
- guidance touchpoints (playbook KB, escalation drill sessions) and return after shift gaps.

Evidence should capture non-linear ticket events, idle gaps between shifts, routing mistakes recovered, branching decisions, and outcomes tied to certification competency — not a single linear training path.`;

const HELPHIVE_ACTIONS: SimulationAction[] = [
  {
    id: "enroll_in_certification",
    label: "Enroll in certification",
    description: "Join Q2 escalation competency program.",
    category: "onboarding",
    blockHint: "Program enrollment",
    cta: "Enroll",
    kind: "evidence",
    dimension: "program_enrollment",
    outcome: "success",
  },
  {
    id: "accept_evaluation_rubric",
    label: "Accept evaluation rubric",
    description: "Acknowledge SLA, tone, and documentation criteria.",
    category: "onboarding",
    blockHint: "Rubric acceptance",
    cta: "Accept rubric",
    kind: "evidence",
    dimension: "program_enrollment",
    outcome: "success",
  },
  {
    id: "skip_training_module",
    label: "Skip training module",
    description: "Veteran agent skips video and jumps to live scenarios.",
    category: "onboarding",
    blockHint: "Experienced path",
    cta: "Skip module",
    kind: "evidence",
    dimension: "self_directed_cert",
    outcome: "partial",
  },
  {
    id: "receive_slack_escalation",
    label: "Receive Slack escalation",
    description: "Priority customer pings #support-escalations.",
    category: "integrations",
    blockHint: "Slack escalation",
    cta: "Accept ticket",
    kind: "evidence",
    dimension: "channel_intake",
    outcome: "success",
  },
  {
    id: "pull_zendesk_context",
    label: "Pull Zendesk context",
    description: "Load full ticket history and prior CSAT scores.",
    category: "integrations",
    blockHint: "Zendesk context",
    cta: "Load history",
    kind: "evidence",
    dimension: "channel_intake",
    outcome: "success",
  },
  {
    id: "misroute_priority_queue",
    label: "Misroute priority queue",
    description: "Send P1 ticket to general queue by mistake.",
    category: "integrations",
    blockHint: "Routing mistake",
    cta: "Route wrong queue",
    kind: "evidence",
    repeatable: true,
    dimension: "routing_recovery",
    outcome: "struggle",
  },
  {
    id: "fix_priority_route",
    label: "Fix priority route",
    description: "Reassign to P1 queue and notify on-call lead.",
    category: "integrations",
    blockHint: "Routing recovery",
    cta: "Fix route",
    kind: "evidence",
    suggestedAfter: ["misroute_priority_queue"],
    dimension: "routing_recovery",
    outcome: "success",
  },
  {
    id: "apply_deescalation_macro",
    label: "Apply de-escalation macro",
    description: "Use approved tone template for angry enterprise customer.",
    category: "projects",
    blockHint: "De-escalation macro",
    cta: "Apply macro",
    kind: "evidence",
    dimension: "playbook_execution",
    outcome: "success",
  },
  {
    id: "follow_escalation_tree",
    label: "Follow escalation tree",
    description: "Walk billing-dispute branch to finance liaison step.",
    category: "projects",
    blockHint: "Escalation tree",
    cta: "Follow tree",
    kind: "evidence",
    dimension: "playbook_execution",
    outcome: "partial",
  },
  {
    id: "document_root_cause",
    label: "Document root cause",
    description: "Log systemic issue linked to recurring outage reports.",
    category: "projects",
    blockHint: "Root cause doc",
    cta: "Save RCA",
    kind: "evidence",
    dimension: "documentation",
    outcome: "success",
  },
  {
    id: "escalate_to_team_lead",
    label: "Escalate to team lead",
    description: "Hand off enterprise renewal risk to shift lead.",
    category: "team",
    blockHint: "Lead escalation",
    cta: "Escalate lead",
    kind: "evidence",
    dimension: "supervision_chain",
    outcome: "success",
  },
  {
    id: "request_manager_shadow",
    label: "Request manager shadow",
    description: "Ask manager to observe high-risk de-escalation call.",
    category: "team",
    blockHint: "Manager shadow",
    cta: "Request shadow",
    kind: "evidence",
    dimension: "supervision_chain",
    outcome: "success",
  },
  {
    id: "handoff_to_specialist",
    label: "Hand off to specialist",
    description: "Transfer technical escalation to L2 engineer queue.",
    category: "team",
    blockHint: "Specialist handoff",
    cta: "Hand off",
    kind: "evidence",
    dimension: "permissions",
    outcome: "partial",
  },
  {
    id: "resolve_within_sla",
    label: "Resolve within SLA",
    description: "Close P1 ticket under 4-hour first-response SLA.",
    category: "activation",
    blockHint: "SLA resolution",
    cta: "Resolve ticket",
    kind: "evidence",
    dimension: "certification",
    outcome: "success",
  },
  {
    id: "pass_qa_evaluation",
    label: "Pass QA evaluation",
    description: "Score meets rubric on tone, accuracy, and documentation.",
    category: "activation",
    blockHint: "QA pass",
    cta: "Record QA pass",
    kind: "evidence",
    dimension: "certification",
    outcome: "success",
  },
  {
    id: "view_team_lead_program",
    label: "View team lead program",
    description: "Open advanced certification after passing escalation track.",
    category: "activation",
    blockHint: "Advancement signal",
    cta: "View program",
    kind: "evidence",
    dimension: "advancement_signal",
    outcome: "partial",
  },
  {
    id: "search_playbook_kb",
    label: "Search playbook KB",
    description: "Find approved language for service outage apologies.",
    category: "support",
    blockHint: "Playbook KB",
    cta: "Search KB",
    kind: "evidence",
    repeatable: true,
    dimension: "guidance_usage",
    outcome: "partial",
  },
  {
    id: "attend_escalation_drill",
    label: "Attend escalation drill",
    description: "Join live drill on executive customer escalations.",
    category: "support",
    blockHint: "Escalation drill",
    cta: "Join drill",
    kind: "evidence",
    dimension: "guided_learning",
    outcome: "success",
  },
  {
    id: "abandon_ticket_mid_triage",
    label: "Abandon ticket mid-triage",
    description: "Close session before categorizing escalation severity.",
    category: "edge_cases",
    blockHint: "Triage abandonment",
    cta: "Abandon triage",
    kind: "evidence",
    repeatable: true,
    dimension: "drop_off",
    outcome: "failure",
  },
  {
    id: "route_to_wrong_specialist",
    label: "Route to wrong specialist",
    description: "Send billing issue to technical L2 by mistake.",
    category: "edge_cases",
    blockHint: "Handoff mistake",
    cta: "Wrong handoff",
    kind: "evidence",
    dimension: "mistake_recovery",
    outcome: "struggle",
  },
  {
    id: "return_after_shift_gap",
    label: "Return after shift gap",
    description: "Resume certification scenario after days off.",
    category: "edge_cases",
    blockHint: "Shift gap return",
    cta: "Resume shift",
    kind: "evidence",
    repeatable: true,
    dimension: "re_engagement",
    outcome: "partial",
  },
  ...createTimeToolActions(),
];

export const helphiveDemo: EvidenceApiDemoDefinition = {
  id: "helphive",
  productName: "HelpHive",
  integrationName: "helphive-escalation-cert-agent",
  useCase: USE_CASE,
  tagline: "Customer support & ticketing",
  saasCategory: "Customer support",
  description:
    "Certify agents on live escalation handling — SLA pressure, de-escalation playbooks, supervisor handoffs, and QA evaluation.",
  scenarioTitle: "Escalation handling certification",
  scenarioIntro: SCENARIO_INTRO,
  workspaceDescription: "HelpHive escalation handling certification program",
  initials: "HH",
  accent: "amber",
  evalDefinition: EVAL_DEFINITION,
  workspacePrompt: `Escalation handling certification verification for HelpHive, a customer support platform.
Agents may take non-linear paths: skip training, pull context in different order, apply macros before escalation trees, misroute queues, abandon and return after shift gaps.
Verify certification competency across channel intake, playbook execution, supervision, SLA resolution, and guidance — not a single linear training checklist.
Create assessable blocks for each competency dimension (enrollment, channels, playbooks, supervision, certification, guidance/exceptions).`,
  modelDocFilename: "helphive-eval-model.md",
  modelDoc: buildModelDoc(
    {
      productName: "HelpHive",
      integrationName: "helphive-escalation-cert-agent",
      evalDefinition: EVAL_DEFINITION,
      modelDocFilename: "helphive-eval-model.md",
      useCase: USE_CASE,
      scenarioIntro: SCENARIO_INTRO,
    },
    `| program_enrollment | Certification enroll and rubric acceptance |
| channel_intake | Slack escalation and Zendesk context |
| routing_recovery | Priority queue misroute recovery |
| playbook_execution | De-escalation macros and escalation trees |
| documentation | Root-cause and RCA logging |
| supervision_chain | Lead escalation and manager shadow |
| certification | In-SLA resolution and QA pass |
| guidance_usage | Playbook KB and escalation drills |
| mistake_recovery | Wrong handoffs, abandoned triage |`
  ),
  toolName: "helphive",
  simulatorToolName: "helphive_events",
  schemaVersion: "helphive_evidence_v1",
  evidenceGoals: ["escalation_certification", "sla_compliance", "playbook_execution", "multidimensional_cert"],
  integrationHints: {
    event_verbs: ["time_gap_elapsed", "receive_slack_escalation", "escalate_to_team_lead"],
    goals: ["escalation_certification", "agent_quality"],
  },
  partnerDescription:
    "HelpHive partner integration that emits support escalation events and uploads evidence to OpenLesson.",
  integrationSkillContext: "HelpHive escalation handling certification integration",
  categoryMeta: {
    onboarding: {
      label: "Program setup",
      description: "Enrollment, rubric, training path — veterans skip ahead.",
    },
    integrations: {
      label: "Channel context",
      description: "Slack escalations, Zendesk history, priority routing.",
    },
    projects: {
      label: "Playbooks",
      description: "De-escalation macros, escalation trees, RCA documentation.",
    },
    team: {
      label: "Supervision",
      description: "Lead escalation, manager shadow, specialist handoff.",
    },
    activation: {
      label: "Certification",
      description: "SLA resolution, QA pass, advancement signals.",
    },
    support: {
      label: "Guidance",
      description: "Playbook knowledge base and escalation drills.",
    },
    edge_cases: {
      label: "Exceptions & gaps",
      description: "Abandoned triage, wrong handoffs, shift-gap returns.",
    },
    simulation_tools: {
      label: "Calendar gaps",
      description: "Record idle time between shifts and review cycles.",
    },
  },
  categoryOrder: STANDARD_CATEGORY_ORDER,
  actions: HELPHIVE_ACTIONS,
};