import {
  buildModelDoc,
  createTimeToolActions,
  type EvidenceApiDemoDefinition,
  STANDARD_CATEGORY_ORDER,
} from "../demo-definition";
import type { SimulationAction } from "../types";

const USE_CASE = "Month-end close certification";
const SCENARIO_INTRO =
  "Accountants complete a **finance close certification program** — branching across period open, data feeds, reconciliations, adjustments, reviewer sign-off, and exception handling. Order varies by team maturity and close calendar pressure.";

const EVAL_DEFINITION = `Verify that finance operators can execute a compliant month-end close on LedgerLine across a non-linear close surface:
- period open, close-owner assignment, and checklist posture (guided vs experienced self-serve),
- data feeds (bank, subledger, payroll) with cutoff correctness and recovery from misconfiguration,
- close workflows (cash reconciliation, accruals, flux analysis, adjusting entries),
- reviewer chain (controller review, auditor read-only, delegated sign-off),
- certification milestones (period lock, close package publication, audit-trail readiness),
- guidance touchpoints (close playbook, controller office hours) and return after calendar delays.

Evidence should capture non-linear close events, idle gaps between close days, errors recovered, branching decisions, and outcomes tied to certification readiness — not a single linear checklist.`;

const LEDGERLINE_ACTIONS: SimulationAction[] = [
  {
    id: "open_close_period",
    label: "Open close period",
    description: "Start February close and assign period owner.",
    category: "onboarding",
    blockHint: "Period open",
    cta: "Open period",
    kind: "evidence",
    dimension: "period_setup",
    outcome: "success",
  },
  {
    id: "assign_close_owner",
    label: "Assign close owner",
    description: "Designate staff accountant as period lead.",
    category: "onboarding",
    blockHint: "Close ownership",
    cta: "Assign owner",
    kind: "evidence",
    dimension: "period_setup",
    outcome: "success",
  },
  {
    id: "skip_close_checklist",
    label: "Skip standard checklist",
    description: "Experienced team bypasses template and works from memory.",
    category: "onboarding",
    blockHint: "Self-directed close",
    cta: "Skip checklist",
    kind: "evidence",
    dimension: "self_directed_close",
    outcome: "partial",
  },
  {
    id: "sync_bank_feed",
    label: "Sync bank feed",
    description: "Import checking transactions through close cutoff.",
    category: "integrations",
    blockHint: "Bank feed sync",
    cta: "Sync feed",
    kind: "evidence",
    dimension: "data_feed_connect",
    outcome: "success",
  },
  {
    id: "import_payroll_subledger",
    label: "Import payroll subledger",
    description: "Load accrued payroll from HRIS export.",
    category: "integrations",
    blockHint: "Payroll import",
    cta: "Import subledger",
    kind: "evidence",
    dimension: "data_feed_connect",
    outcome: "success",
  },
  {
    id: "misconfigure_cutoff_date",
    label: "Misconfigure cutoff date",
    description: "Set bank feed cutoff one day early, missing month-end txs.",
    category: "integrations",
    blockHint: "Cutoff misconfiguration",
    cta: "Save wrong cutoff",
    kind: "evidence",
    repeatable: true,
    dimension: "feed_recovery",
    outcome: "struggle",
  },
  {
    id: "fix_cutoff_date",
    label: "Fix cutoff date",
    description: "Correct cutoff and re-import missing transactions.",
    category: "integrations",
    blockHint: "Cutoff recovery",
    cta: "Fix cutoff",
    kind: "evidence",
    suggestedAfter: ["misconfigure_cutoff_date"],
    dimension: "feed_recovery",
    outcome: "success",
  },
  {
    id: "reconcile_cash_account",
    label: "Reconcile cash account",
    description: "Match all bank lines for operating account.",
    category: "projects",
    blockHint: "Cash reconciliation",
    cta: "Finish reconcile",
    kind: "evidence",
    dimension: "reconciliation",
    outcome: "success",
  },
  {
    id: "post_accrual_entry",
    label: "Post accrual entry",
    description: "Record utilities accrual for uninvoiced period spend.",
    category: "projects",
    blockHint: "Accrual posting",
    cta: "Post accrual",
    kind: "evidence",
    dimension: "adjusting_entries",
    outcome: "success",
  },
  {
    id: "run_flux_analysis",
    label: "Run flux analysis",
    description: "Explain >10% MoM variance on hosting expense.",
    category: "projects",
    blockHint: "Flux analysis",
    cta: "Document flux",
    kind: "evidence",
    dimension: "analysis",
    outcome: "partial",
  },
  {
    id: "submit_to_controller",
    label: "Submit to controller",
    description: "Send close package for controller review.",
    category: "team",
    blockHint: "Controller review",
    cta: "Submit package",
    kind: "evidence",
    dimension: "review_chain",
    outcome: "success",
  },
  {
    id: "add_auditor_viewer",
    label: "Add auditor (viewer)",
    description: "Grant external auditor read-only close access.",
    category: "team",
    blockHint: "Auditor access",
    cta: "Grant viewer",
    kind: "evidence",
    dimension: "permissions",
    outcome: "success",
  },
  {
    id: "delegate_sign_off",
    label: "Delegate sign-off",
    description: "Controller delegates final sign-off while traveling.",
    category: "team",
    blockHint: "Delegated sign-off",
    cta: "Delegate approval",
    kind: "evidence",
    dimension: "permissions",
    outcome: "partial",
  },
  {
    id: "lock_accounting_period",
    label: "Lock accounting period",
    description: "Freeze GL after all reconciliations pass.",
    category: "activation",
    blockHint: "Period lock",
    cta: "Lock period",
    kind: "evidence",
    dimension: "certification",
    outcome: "success",
  },
  {
    id: "publish_close_package",
    label: "Publish close package",
    description: "Distribute final close binder to leadership.",
    category: "activation",
    blockHint: "Close publication",
    cta: "Publish package",
    kind: "evidence",
    dimension: "certification",
    outcome: "success",
  },
  {
    id: "request_audit_trail_export",
    label: "Request audit trail export",
    description: "Trigger enterprise audit log export for compliance.",
    category: "activation",
    blockHint: "Audit readiness",
    cta: "Export trail",
    kind: "evidence",
    dimension: "compliance_signal",
    outcome: "partial",
  },
  {
    id: "open_close_playbook",
    label: "Open close playbook",
    description: "Reference standard close procedures for suspense accounts.",
    category: "support",
    blockHint: "Close playbook",
    cta: "Open playbook",
    kind: "evidence",
    repeatable: true,
    dimension: "guidance_usage",
    outcome: "partial",
  },
  {
    id: "attend_close_office_hours",
    label: "Join controller office hours",
    description: "Attend live session on flux documentation standards.",
    category: "support",
    blockHint: "Office hours",
    cta: "Join session",
    kind: "evidence",
    dimension: "guided_learning",
    outcome: "success",
  },
  {
    id: "abandon_reconciliation",
    label: "Abandon reconciliation",
    description: "Close tab mid-reconcile with 12 unmatched lines remaining.",
    category: "edge_cases",
    blockHint: "Close abandonment",
    cta: "Abandon reconcile",
    kind: "evidence",
    repeatable: true,
    dimension: "drop_off",
    outcome: "failure",
  },
  {
    id: "post_to_wrong_period",
    label: "Post to wrong period",
    description: "Accidentally book entry to prior month before lock.",
    category: "edge_cases",
    blockHint: "Period mistake",
    cta: "Post wrong period",
    kind: "evidence",
    dimension: "mistake_recovery",
    outcome: "struggle",
  },
  {
    id: "return_after_close_delay",
    label: "Return after close delay",
    description: "Resume close work after a multi-day gap.",
    category: "edge_cases",
    blockHint: "Delayed return",
    cta: "Resume close",
    kind: "evidence",
    repeatable: true,
    dimension: "re_engagement",
    outcome: "partial",
  },
  ...createTimeToolActions(),
];

export const ledgerlineDemo: EvidenceApiDemoDefinition = {
  id: "ledgerline",
  productName: "LedgerLine",
  integrationName: "ledgerline-close-agent",
  useCase: USE_CASE,
  tagline: "SMB accounting & finance ops",
  saasCategory: "FinTech",
  description:
    "Certify a finance team's month-end close — reconciliations, accruals, reviewer sign-off, and exception recovery under deadline pressure.",
  scenarioTitle: "Month-end close certification",
  scenarioIntro: SCENARIO_INTRO,
  workspaceDescription: "LedgerLine month-end close certification program",
  initials: "LL",
  accent: "emerald",
  evalDefinition: EVAL_DEFINITION,
  workspacePrompt: `Month-end close certification verification for LedgerLine, an SMB accounting platform.
Close operators may take non-linear paths: skip checklists, sync feeds in different order, reconcile before accruals, misconfigure cutoffs, abandon and return days later.
Verify certification readiness across data feeds, close workflows, review chain, sign-off, and guidance — not a single linear close checklist.
Create assessable blocks for each competency dimension (period setup, feeds, workflows, review, certification, guidance/exceptions).`,
  modelDocFilename: "ledgerline-eval-model.md",
  modelDoc: buildModelDoc(
    {
      productName: "LedgerLine",
      integrationName: "ledgerline-close-agent",
      evalDefinition: EVAL_DEFINITION,
      modelDocFilename: "ledgerline-eval-model.md",
      useCase: USE_CASE,
      scenarioIntro: SCENARIO_INTRO,
    },
    `| period_setup | Open period, assign owner, self-directed close |
| data_feed_connect | Bank, payroll, subledger imports |
| feed_recovery | Cutoff misconfiguration recovery |
| reconciliation | Cash and suspense reconciliations |
| adjusting_entries | Accruals and period adjustments |
| analysis | Flux and variance documentation |
| review_chain | Controller and auditor review |
| certification | Period lock and close package |
| guidance_usage | Playbook and office hours |
| mistake_recovery | Wrong-period posts, abandoned reconciles |`
  ),
  toolName: "ledgerline",
  simulatorToolName: "ledgerline_events",
  schemaVersion: "ledgerline_evidence_v1",
  evidenceGoals: ["close_certification", "reconciliation", "review_signoff", "multidimensional_close"],
  integrationHints: {
    event_verbs: ["time_gap_elapsed", "sync_bank_feed", "submit_to_controller"],
    goals: ["close_certification", "month_end_close"],
  },
  partnerDescription:
    "LedgerLine partner integration that emits close-workflow events and uploads evidence to OpenLesson.",
  integrationSkillContext: "LedgerLine month-end close certification integration",
  categoryMeta: {
    onboarding: {
      label: "Close preparation",
      description: "Open period, assign owner, checklist — rarely the same sequence twice.",
    },
    integrations: {
      label: "Data feeds",
      description: "Bank, payroll, subledgers — sync and recover cutoff mistakes.",
    },
    projects: {
      label: "Close workflows",
      description: "Reconciliations, accruals, flux analysis, adjusting entries.",
    },
    team: {
      label: "Review chain",
      description: "Controller review, auditor access, delegated sign-off.",
    },
    activation: {
      label: "Certification",
      description: "Period lock, close package, audit-trail readiness.",
    },
    support: {
      label: "Guidance",
      description: "Close playbook and controller office hours.",
    },
    edge_cases: {
      label: "Exceptions & delays",
      description: "Abandoned reconciles, wrong-period posts, delayed returns.",
    },
    simulation_tools: {
      label: "Calendar gaps",
      description: "Record idle time between close work sessions.",
    },
  },
  categoryOrder: STANDARD_CATEGORY_ORDER,
  actions: LEDGERLINE_ACTIONS,
};