import {
  buildModelDoc,
  createTimeToolActions,
  type EvidenceApiDemoDefinition,
  STANDARD_CATEGORY_ORDER,
} from "../demo-definition";
import type { SimulationAction } from "../types";

const USE_CASE = "Launch instrumentation audit";
const SCENARIO_INTRO =
  "Product teams run a **pre-launch instrumentation audit** — branching across scope definition, pipeline wiring, funnel coverage checks, stakeholder review, and go/no-go sign-off before release. Paths diverge by team size and launch risk.";

const EVAL_DEFINITION = `Verify that a product team can pass a launch instrumentation audit on MetricPulse across a non-linear readiness surface:
- audit scope, staging snippet deployment, and coverage checklist posture (template vs custom),
- pipeline connections (Segment, warehouse, SDK) with schema correctness and recovery,
- coverage artifacts (signup funnel, revenue events, launch alert thresholds),
- stakeholder review (PM sign-off, exec read-only, delegated dashboard ownership),
- go/no-go milestones (coverage threshold met, launch checklist signed, retention tier viewed),
- guidance touchpoints (instrumentation docs, launch review office hours) and return after review delays.

Evidence should capture non-linear audit events, idle gaps between review cycles, schema fixes, branching decisions, and outcomes tied to launch readiness — not a single linear setup guide.`;

const METRICPULSE_ACTIONS: SimulationAction[] = [
  {
    id: "define_launch_scope",
    label: "Define launch scope",
    description: "Document v2.4 launch events and success metrics.",
    category: "onboarding",
    blockHint: "Audit scope",
    cta: "Save scope",
    kind: "evidence",
    dimension: "audit_scope",
    outcome: "success",
  },
  {
    id: "deploy_staging_snippet",
    label: "Deploy staging snippet",
    description: "Install SDK on staging with launch feature flag.",
    category: "onboarding",
    blockHint: "Staging deployment",
    cta: "Deploy snippet",
    kind: "evidence",
    dimension: "instrumentation_deploy",
    outcome: "success",
  },
  {
    id: "skip_audit_template",
    label: "Skip audit template",
    description: "Senior analyst skips checklist and audits ad hoc.",
    category: "onboarding",
    blockHint: "Ad hoc audit",
    cta: "Skip template",
    kind: "evidence",
    dimension: "self_directed_audit",
    outcome: "partial",
  },
  {
    id: "connect_segment_source",
    label: "Connect Segment source",
    description: "Wire product analytics stream for launch events.",
    category: "integrations",
    blockHint: "Segment pipeline",
    cta: "Connect Segment",
    kind: "evidence",
    dimension: "pipeline_connect",
    outcome: "success",
  },
  {
    id: "connect_warehouse_export",
    label: "Connect warehouse export",
    description: "Enable nightly event export to Snowflake.",
    category: "integrations",
    blockHint: "Warehouse pipeline",
    cta: "Enable export",
    kind: "evidence",
    dimension: "pipeline_connect",
    outcome: "success",
  },
  {
    id: "misconfigure_event_property",
    label: "Misconfigure event property",
    description: "Map purchase_amount as string instead of number.",
    category: "integrations",
    blockHint: "Schema defect",
    cta: "Save wrong type",
    kind: "evidence",
    repeatable: true,
    dimension: "schema_recovery",
    outcome: "struggle",
  },
  {
    id: "fix_event_property",
    label: "Fix event property",
    description: "Correct schema and backfill staging events.",
    category: "integrations",
    blockHint: "Schema fix",
    cta: "Fix property",
    kind: "evidence",
    suggestedAfter: ["misconfigure_event_property"],
    dimension: "schema_recovery",
    outcome: "success",
  },
  {
    id: "validate_signup_funnel",
    label: "Validate signup funnel",
    description: "Confirm all launch funnel steps fire in staging.",
    category: "projects",
    blockHint: "Funnel validation",
    cta: "Run validation",
    kind: "evidence",
    dimension: "coverage_check",
    outcome: "success",
  },
  {
    id: "add_revenue_event",
    label: "Add revenue event",
    description: "Instrument paid conversion with plan metadata.",
    category: "projects",
    blockHint: "Revenue instrumentation",
    cta: "Add event",
    kind: "evidence",
    dimension: "coverage_check",
    outcome: "partial",
  },
  {
    id: "configure_launch_alert",
    label: "Configure launch alert",
    description: "Alert if signup completion drops 15% day-one post-launch.",
    category: "projects",
    blockHint: "Launch alert",
    cta: "Save alert",
    kind: "evidence",
    dimension: "monitoring_setup",
    outcome: "success",
  },
  {
    id: "share_audit_with_pm",
    label: "Share audit with PM",
    description: "Send coverage report to product lead for review.",
    category: "team",
    blockHint: "PM review",
    cta: "Share report",
    kind: "evidence",
    dimension: "stakeholder_review",
    outcome: "success",
  },
  {
    id: "invite_exec_viewer",
    label: "Invite exec viewer",
    description: "Grant CPO read-only launch dashboard access.",
    category: "team",
    blockHint: "Executive review",
    cta: "Invite viewer",
    kind: "evidence",
    dimension: "permissions",
    outcome: "success",
  },
  {
    id: "delegate_dashboard_owner",
    label: "Delegate dashboard owner",
    description: "Transfer launch war-room dashboard to analytics lead.",
    category: "team",
    blockHint: "Ownership transfer",
    cta: "Delegate owner",
    kind: "evidence",
    dimension: "permissions",
    outcome: "partial",
  },
  {
    id: "pass_coverage_threshold",
    label: "Pass coverage threshold",
    description: "Meet 95% required-event coverage in staging audit.",
    category: "activation",
    blockHint: "Coverage milestone",
    cta: "Mark passed",
    kind: "evidence",
    dimension: "go_no_go",
    outcome: "success",
  },
  {
    id: "sign_launch_checklist",
    label: "Sign launch checklist",
    description: "PM and analytics jointly sign go/no-go checklist.",
    category: "activation",
    blockHint: "Launch sign-off",
    cta: "Sign checklist",
    kind: "evidence",
    dimension: "go_no_go",
    outcome: "success",
  },
  {
    id: "view_retention_tier",
    label: "View retention tier",
    description: "Open enterprise pricing for extended event retention.",
    category: "activation",
    blockHint: "Tier evaluation",
    cta: "View pricing",
    kind: "evidence",
    dimension: "expansion_signal",
    outcome: "partial",
  },
  {
    id: "search_instrumentation_docs",
    label: "Search instrumentation docs",
    description: "Find guidance on identity stitching for launch cohorts.",
    category: "support",
    blockHint: "Documentation",
    cta: "Open docs",
    kind: "evidence",
    repeatable: true,
    dimension: "guidance_usage",
    outcome: "partial",
  },
  {
    id: "attend_launch_review_hours",
    label: "Join launch review hours",
    description: "Attend live session on funnel coverage standards.",
    category: "support",
    blockHint: "Review office hours",
    cta: "Join session",
    kind: "evidence",
    dimension: "guided_learning",
    outcome: "success",
  },
  {
    id: "abandon_staging_validation",
    label: "Abandon staging validation",
    description: "Exit audit before verifying final funnel step.",
    category: "edge_cases",
    blockHint: "Audit abandonment",
    cta: "Abandon audit",
    kind: "evidence",
    repeatable: true,
    dimension: "drop_off",
    outcome: "failure",
  },
  {
    id: "share_draft_externally",
    label: "Share draft externally",
    description: "Accidentally share pre-launch metrics link outside org.",
    category: "edge_cases",
    blockHint: "Sharing mistake",
    cta: "Share wrong link",
    kind: "evidence",
    dimension: "mistake_recovery",
    outcome: "struggle",
  },
  {
    id: "return_after_review_delay",
    label: "Return after review delay",
    description: "Resume audit after a multi-day stakeholder delay.",
    category: "edge_cases",
    blockHint: "Delayed return",
    cta: "Resume audit",
    kind: "evidence",
    repeatable: true,
    dimension: "re_engagement",
    outcome: "partial",
  },
  ...createTimeToolActions(),
];

export const metricpulseDemo: EvidenceApiDemoDefinition = {
  id: "metricpulse",
  productName: "MetricPulse",
  integrationName: "metricpulse-launch-audit-agent",
  useCase: USE_CASE,
  tagline: "Product analytics & insights",
  saasCategory: "Analytics / BI",
  description:
    "Run a pre-launch instrumentation audit — validate event schemas, funnel coverage, alerts, and go/no-go sign-off before ship.",
  scenarioTitle: "Launch instrumentation audit",
  scenarioIntro: SCENARIO_INTRO,
  workspaceDescription: "MetricPulse launch instrumentation audit",
  initials: "MP",
  accent: "violet",
  evalDefinition: EVAL_DEFINITION,
  workspacePrompt: `Launch instrumentation audit verification for MetricPulse, a product analytics platform.
Audit teams may take non-linear paths: skip templates, connect pipelines in different order, validate funnels before revenue events, misconfigure schemas, abandon and return days later.
Verify launch readiness across pipelines, coverage checks, stakeholder review, go/no-go, and guidance — not a single linear instrumentation guide.
Create assessable blocks for each competency dimension (scope, pipelines, coverage, review, go/no-go, guidance/exceptions).`,
  modelDocFilename: "metricpulse-eval-model.md",
  modelDoc: buildModelDoc(
    {
      productName: "MetricPulse",
      integrationName: "metricpulse-launch-audit-agent",
      evalDefinition: EVAL_DEFINITION,
      modelDocFilename: "metricpulse-eval-model.md",
      useCase: USE_CASE,
      scenarioIntro: SCENARIO_INTRO,
    },
    `| audit_scope | Launch scope and staging deployment |
| pipeline_connect | Segment, warehouse, SDK wiring |
| schema_recovery | Event property misconfiguration fixes |
| coverage_check | Funnel and revenue event validation |
| monitoring_setup | Launch alert configuration |
| stakeholder_review | PM and executive review |
| go_no_go | Coverage threshold and checklist sign-off |
| guidance_usage | Docs and launch review hours |
| mistake_recovery | External share mistakes, abandoned audits |`
  ),
  toolName: "metricpulse",
  simulatorToolName: "metricpulse_events",
  schemaVersion: "metricpulse_evidence_v1",
  evidenceGoals: ["launch_readiness", "instrumentation_coverage", "go_no_go", "multidimensional_audit"],
  integrationHints: {
    event_verbs: ["time_gap_elapsed", "connect_segment_source", "validate_signup_funnel"],
    goals: ["launch_readiness", "instrumentation_audit"],
  },
  partnerDescription:
    "MetricPulse partner integration that emits instrumentation audit events and uploads evidence to OpenLesson.",
  integrationSkillContext: "MetricPulse launch instrumentation audit integration",
  categoryMeta: {
    onboarding: {
      label: "Audit preparation",
      description: "Scope, staging deploy, checklist — order varies by team.",
    },
    integrations: {
      label: "Data pipelines",
      description: "Segment, warehouse, SDK — connect and fix schema defects.",
    },
    projects: {
      label: "Coverage checks",
      description: "Funnel validation, revenue events, launch alerts.",
    },
    team: {
      label: "Stakeholder review",
      description: "PM sign-off, exec viewers, dashboard ownership.",
    },
    activation: {
      label: "Go / no-go",
      description: "Coverage thresholds, checklist sign-off, tier evaluation.",
    },
    support: {
      label: "Guidance",
      description: "Instrumentation docs and launch review hours.",
    },
    edge_cases: {
      label: "Exceptions & delays",
      description: "Abandoned audits, sharing mistakes, delayed returns.",
    },
    simulation_tools: {
      label: "Calendar gaps",
      description: "Record idle time between review cycles.",
    },
  },
  categoryOrder: STANDARD_CATEGORY_ORDER,
  actions: METRICPULSE_ACTIONS,
};