import {
  buildModelDoc,
  createTimeToolActions,
  type ProofOfWorkApiDemoDefinition,
  STANDARD_CATEGORY_ORDER,
} from "../demo-definition";
import type { SimulationAction } from "../types";

const USE_CASE = "FP&A quarter-close spreadsheet certification";
const SCENARIO_INTRO =
  "Analysts complete certification entirely inside **GridWorks** — build workbooks, wire data feeds, write formulas, pivot variance, share for review, and publish close snapshots while every in-app action streams Proof-of-Work API events automatically.";

const EVAL_DEFINITION = `Verify that FP&A operators can certify on GridWorks across a non-linear close surface:
- workbook creation, owner assignment, and template posture (guided vs experienced skip),
- data ingestion (CSV import, API connectors) with date-filter correctness and recovery,
- modeling workflows (SUM formulas, pivot tables, charts, saved filter views),
- collaboration chain (share, lock ranges, publish snapshot, audit export),
- guidance touchpoints (formula guide, analyst sessions) and return after idle gaps,
- formula mistakes (#REF breaks) detected and repaired in-product.

Proof of work should capture non-linear spreadsheet actions, idle calendar gaps, errors recovered, and outcomes tied to close readiness — surfaced in score cards with coaching overlays inside the live app.`;

const GRIDWORKS_ACTIONS: SimulationAction[] = [
  {
    id: "create_workbook",
    label: "Create workbook",
    description: "Start a new quarter-close workbook from template.",
    category: "onboarding",
    blockHint: "Workbook setup",
    cta: "Create",
    kind: "proof_of_work",
    dimension: "workbook_setup",
    outcome: "success",
  },
  {
    id: "assign_close_owner",
    label: "Assign close owner",
    description: "Designate analyst as workbook owner on close sheet.",
    category: "onboarding",
    blockHint: "Ownership",
    cta: "Assign owner",
    kind: "proof_of_work",
    dimension: "workbook_setup",
    outcome: "success",
  },
  {
    id: "skip_template_wizard",
    label: "Skip template wizard",
    description: "Experienced analyst bypasses guided template setup.",
    category: "onboarding",
    blockHint: "Self-directed setup",
    cta: "Skip wizard",
    kind: "proof_of_work",
    dimension: "self_directed_modeling",
    outcome: "partial",
  },
  {
    id: "import_csv_feed",
    label: "Import CSV feed",
    description: "Load revenue rows from exported billing CSV.",
    category: "integrations",
    blockHint: "CSV import",
    cta: "Import CSV",
    kind: "proof_of_work",
    dimension: "data_ingestion",
    outcome: "success",
  },
  {
    id: "connect_api_source",
    label: "Connect API source",
    description: "Attach live billing API connector to workbook.",
    category: "integrations",
    blockHint: "API connector",
    cta: "Connect API",
    kind: "proof_of_work",
    dimension: "data_ingestion",
    outcome: "success",
  },
  {
    id: "wrong_date_filter",
    label: "Wrong date filter",
    description: "Apply filter that excludes month-end rows.",
    category: "integrations",
    blockHint: "Filter mistake",
    cta: "Apply wrong filter",
    kind: "proof_of_work",
    repeatable: true,
    dimension: "filter_recovery",
    outcome: "struggle",
  },
  {
    id: "fix_date_filter",
    label: "Fix date filter",
    description: "Correct Q1 slice after filter mistake.",
    category: "integrations",
    blockHint: "Filter recovery",
    cta: "Fix filter",
    kind: "proof_of_work",
    suggestedAfter: ["wrong_date_filter"],
    dimension: "filter_recovery",
    outcome: "success",
  },
  {
    id: "write_sum_formula",
    label: "Write SUM formula",
    description: "Total ARR and services columns with SUM.",
    category: "projects",
    blockHint: "Formula authoring",
    cta: "Write SUM",
    kind: "proof_of_work",
    dimension: "modeling",
    outcome: "success",
  },
  {
    id: "build_pivot_table",
    label: "Build pivot table",
    description: "Summarize expense variance in pivot view.",
    category: "projects",
    blockHint: "Pivot modeling",
    cta: "Insert pivot",
    kind: "proof_of_work",
    dimension: "modeling",
    outcome: "success",
  },
  {
    id: "add_variance_chart",
    label: "Add variance chart",
    description: "Chart budget vs actual on expense sheet.",
    category: "projects",
    blockHint: "Visualization",
    cta: "Add chart",
    kind: "proof_of_work",
    dimension: "analysis",
    outcome: "partial",
  },
  {
    id: "apply_filter_view",
    label: "Apply filter view",
    description: "Save controller review slice as named view.",
    category: "projects",
    blockHint: "Saved views",
    cta: "Save view",
    kind: "proof_of_work",
    dimension: "analysis",
    outcome: "success",
  },
  {
    id: "share_workbook",
    label: "Share workbook",
    description: "Invite controller with comment access.",
    category: "team",
    blockHint: "Collaboration",
    cta: "Share",
    kind: "proof_of_work",
    dimension: "review_chain",
    outcome: "success",
  },
  {
    id: "lock_formula_cells",
    label: "Lock formula cells",
    description: "Protect formula ranges before review.",
    category: "team",
    blockHint: "Range protection",
    cta: "Lock cells",
    kind: "proof_of_work",
    dimension: "review_chain",
    outcome: "success",
  },
  {
    id: "publish_snapshot",
    label: "Publish snapshot",
    description: "Publish immutable close snapshot to leadership.",
    category: "activation",
    blockHint: "Close publication",
    cta: "Publish",
    kind: "proof_of_work",
    dimension: "certification",
    outcome: "success",
  },
  {
    id: "export_audit_log",
    label: "Export audit log",
    description: "Download enterprise change log for compliance.",
    category: "activation",
    blockHint: "Audit readiness",
    cta: "Export log",
    kind: "proof_of_work",
    dimension: "compliance_signal",
    outcome: "partial",
  },
  {
    id: "open_formula_guide",
    label: "Open formula guide",
    description: "Reference in-app formula documentation.",
    category: "support",
    blockHint: "Formula guide",
    cta: "Open guide",
    kind: "proof_of_work",
    repeatable: true,
    dimension: "guidance_usage",
    outcome: "partial",
  },
  {
    id: "join_analyst_session",
    label: "Join analyst session",
    description: "Attend live session on variance documentation.",
    category: "support",
    blockHint: "Office hours",
    cta: "Join session",
    kind: "proof_of_work",
    dimension: "guided_learning",
    outcome: "success",
  },
  {
    id: "break_formula_chain",
    label: "Break formula chain",
    description: "Delete source row and corrupt totals with #REF!.",
    category: "edge_cases",
    blockHint: "Formula break",
    cta: "Break ref",
    kind: "proof_of_work",
    repeatable: true,
    dimension: "mistake_recovery",
    outcome: "struggle",
  },
  {
    id: "fix_broken_reference",
    label: "Fix broken reference",
    description: "Repair #REF! after formula chain break.",
    category: "edge_cases",
    blockHint: "Formula recovery",
    cta: "Fix #REF!",
    kind: "proof_of_work",
    suggestedAfter: ["break_formula_chain"],
    dimension: "mistake_recovery",
    outcome: "success",
  },
  ...createTimeToolActions(),
];

export const gridworksDemo: ProofOfWorkApiDemoDefinition = {
  id: "gridworks",
  productName: "GridWorks",
  integrationName: "gridworks-fpa-agent",
  useCase: USE_CASE,
  tagline: "Model, reconcile, and publish quarter-close workbooks",
  saasCategory: "FP&A spreadsheet",
  description:
    "A full spreadsheet workbench for FP&A close — import feeds, write formulas, pivot variance, collaborate, and publish snapshots with live Proof-of-Work API scoring.",
  scenarioTitle: "Quarter-close spreadsheet certification",
  scenarioIntro: SCENARIO_INTRO,
  workspaceDescription:
    "GridWorks FP&A certification — verify modeling and close competency through in-app workbook usage with continuous Proof-of-Work API uploads and score-driven coaching.",
  initials: "GW",
  accent: "emerald",
  simulatorMode: "app",
  evalDefinition: EVAL_DEFINITION,
  workspacePrompt: `Quarter-close spreadsheet certification for GridWorks, an FP&A modeling platform.
Analysts may take non-linear paths: skip wizards, import before formulas, break and fix references, mis-filter dates, share before locking.
Verify certification readiness across ingestion, modeling, collaboration, publication, and guidance — not a single linear checklist.
Create assessable blocks for each competency dimension.`,
  modelDocFilename: "gridworks-eval-model.md",
  modelDoc: buildModelDoc(
    {
      productName: "GridWorks",
      integrationName: "gridworks-fpa-agent",
      evalDefinition: EVAL_DEFINITION,
      modelDocFilename: "gridworks-eval-model.md",
      useCase: USE_CASE,
      scenarioIntro: SCENARIO_INTRO,
    },
    `| workbook_setup | Create workbook, assign owner, skip wizard |
| data_ingestion | CSV import, API connectors |
| filter_recovery | Date filter mistakes and fixes |
| modeling | SUM formulas, pivots, charts, views |
| review_chain | Share, lock ranges, publish snapshot |
| compliance_signal | Audit log export |
| guidance_usage | Formula guide and analyst sessions |
| mistake_recovery | Broken references and repair |`
  ),
  toolName: "gridworks",
  simulatorToolName: "gridworks_events",
  schemaVersion: "gridworks_evidence_v1",
  proofOfWorkGoals: ["close_certification", "spreadsheet_modeling", "review_signoff", "multidimensional_close"],
  integrationHints: {
    event_verbs: ["time_gap_elapsed", "write_sum_formula", "publish_snapshot"],
    goals: ["close_certification", "quarter_close"],
  },
  partnerDescription:
    "GridWorks partner integration that emits spreadsheet-workflow events and uploads proof of work to Uncertain Systems.",
  integrationSkillContext: "GridWorks FP&A quarter-close certification integration",
  categoryMeta: {
    onboarding: {
      label: "Workbook setup",
      description: "Create workbook, assign owner, template wizard.",
    },
    integrations: {
      label: "Data feeds",
      description: "CSV imports, API connectors, filter recovery.",
    },
    projects: {
      label: "Modeling",
      description: "Formulas, pivots, charts, saved views.",
    },
    team: {
      label: "Collaboration",
      description: "Share workbook and lock formula ranges.",
    },
    activation: {
      label: "Publication",
      description: "Publish snapshot and export audit log.",
    },
    support: {
      label: "Guidance",
      description: "Formula guide and analyst sessions.",
    },
    edge_cases: {
      label: "Formula recovery",
      description: "Broken references and repair flows.",
    },
    simulation_tools: {
      label: "Calendar gaps",
      description: "Record idle time between close sessions.",
    },
  },
  categoryOrder: STANDARD_CATEGORY_ORDER,
  actions: GRIDWORKS_ACTIONS,
};