import {
  buildModelDoc,
  createTimeToolActions,
  type ProofOfWorkApiDemoDefinition,
} from "../demo-definition";
import type { SimulationAction } from "../types";

const USE_CASE = "Resource-gathering city growth certification";
const SCENARIO_INTRO =
  "Mayors grow **Haven Rise** entirely inside the game — survey plots, gather wood and stone, build districts, open markets, and reach city milestones while the integration streams every in-game action as Proof-of-Work API tool events in the background.";

const EVAL_DEFINITION = `Verify that city operators can certify on Haven Rise across a non-linear growth surface:
- settlement founding, plot surveying, and tutorial posture (guided vs veteran skip),
- resource gathering (timber, stone, crops, forage) and storage buffers,
- district building (cottages, farms, roads, granaries),
- trade channels and caravan recovery after misroutes,
- civic records, census, and defense (walls, watchtowers),
- city milestone completion and adaptation after overzoning mistakes,
- re-engagement after idle seasons between play sessions.

Proof of work should capture gather/build/trade decisions, idle gaps, zoning mistakes recovered, branching growth orders, and outcomes tied to city competency — surfaced in score cards with gap repairs and next-step overlays inside the live game.`;

const NEXUSFRONT_ACTIONS: SimulationAction[] = [
  {
    id: "commission_outpost",
    label: "Commission outpost",
    description: "Bring the frontier command node online and accept mission brief.",
    category: "onboarding",
    blockHint: "Outpost commissioning",
    cta: "Commission",
    kind: "proof_of_work",
    dimension: "outpost_setup",
    outcome: "success",
  },
  {
    id: "deploy_scout_drone",
    label: "Deploy scout drone",
    description: "Survey an adjacent city plot.",
    repeatable: true,
    category: "onboarding",
    blockHint: "Sector scouting",
    cta: "Scout sector",
    kind: "proof_of_work",
    dimension: "sector_scouting",
    outcome: "success",
  },
  {
    id: "skip_veteran_briefing",
    label: "Skip veteran briefing",
    description: "Dismiss the guided mission walkthrough and self-direct.",
    category: "onboarding",
    blockHint: "Veteran path",
    cta: "Skip briefing",
    kind: "proof_of_work",
    dimension: "self_directed_command",
    outcome: "partial",
  },
  {
    id: "calibrate_sensors",
    label: "Calibrate sensors",
    description: "Gather timber or sync town instruments.",
    repeatable: true,
    category: "onboarding",
    blockHint: "Sensor calibration",
    cta: "Calibrate",
    kind: "proof_of_work",
    dimension: "outpost_setup",
    outcome: "success",
  },
  {
    id: "establish_beacon",
    label: "Establish beacon",
    description: "Build a cottage or population structure on a plot.",
    repeatable: true,
    category: "projects",
    blockHint: "Beacon network",
    cta: "Build beacon",
    kind: "proof_of_work",
    dimension: "outpost_build",
    outcome: "success",
  },
  {
    id: "deploy_relay_satellite",
    label: "Deploy relay satellite",
    description: "Build a farm or mill on city plots.",
    repeatable: true,
    category: "projects",
    blockHint: "Orbital relay",
    cta: "Launch relay",
    kind: "proof_of_work",
    dimension: "outpost_build",
    outcome: "success",
  },
  {
    id: "expand_supply_depot",
    label: "Expand supply depot",
    description: "Harvest crops from a surveyed field plot.",
    repeatable: true,
    category: "projects",
    blockHint: "Supply depot",
    cta: "Expand depot",
    kind: "proof_of_work",
    dimension: "infrastructure",
    outcome: "success",
  },
  {
    id: "route_energy_grid",
    label: "Route energy grid",
    description: "Balance generators across three sectors.",
    category: "activation",
    blockHint: "Energy routing",
    cta: "Route power",
    kind: "proof_of_work",
    dimension: "resource_allocation",
    outcome: "success",
  },
  {
    id: "stockpile_reserves",
    label: "Stockpile reserves",
    description: "Buffer energy and materials for extended campaign gaps.",
    category: "activation",
    blockHint: "Reserve buffers",
    cta: "Stockpile",
    kind: "proof_of_work",
    dimension: "resource_allocation",
    outcome: "success",
  },
  {
    id: "redeploy_generators",
    label: "Redeploy generators",
    description: "Shift power nodes after sector priority rebalance.",
    category: "activation",
    blockHint: "Generator redeploy",
    cta: "Redeploy",
    kind: "proof_of_work",
    suggestedAfter: ["correct_sector_priority"],
    dimension: "resource_allocation",
    outcome: "success",
  },
  {
    id: "open_trade_channel",
    label: "Open trade channel",
    description: "Negotiate materials exchange with a neighboring colony.",
    category: "integrations",
    blockHint: "Trade diplomacy",
    cta: "Open trade",
    kind: "proof_of_work",
    dimension: "diplomacy",
    outcome: "success",
  },
  {
    id: "dispatch_envoy",
    label: "Dispatch envoy",
    description: "Send diplomatic envoy to a neighboring sector.",
    category: "integrations",
    blockHint: "Envoy dispatch",
    cta: "Send envoy",
    kind: "proof_of_work",
    dimension: "diplomacy",
    outcome: "success",
  },
  {
    id: "misroute_envoy",
    label: "Misroute envoy",
    description: "Route envoy through hostile airspace before correcting course.",
    category: "integrations",
    blockHint: "Envoy recovery",
    cta: "Misroute",
    kind: "proof_of_work",
    repeatable: true,
    dimension: "diplomacy_error",
    outcome: "struggle",
  },
  {
    id: "recover_envoy_route",
    label: "Recover envoy route",
    description: "Correct envoy trajectory after misrouting.",
    category: "integrations",
    blockHint: "Route correction",
    cta: "Recover route",
    kind: "proof_of_work",
    suggestedAfter: ["misroute_envoy"],
    dimension: "adaptation",
    outcome: "success",
  },
  {
    id: "fortify_perimeter",
    label: "Fortify perimeter",
    description: "Harden shields and deploy automated sentries.",
    category: "team",
    blockHint: "Perimeter defense",
    cta: "Fortify",
    kind: "proof_of_work",
    dimension: "defense_posture",
    outcome: "success",
  },
  {
    id: "breach_response_drill",
    label: "Breach response drill",
    description: "Run coalition breach-response simulation with allied units.",
    category: "team",
    blockHint: "Breach drill",
    cta: "Run drill",
    kind: "proof_of_work",
    dimension: "defense_posture",
    outcome: "success",
  },
  {
    id: "assign_watch_rotation",
    label: "Assign watch rotation",
    description: "Quarry stone from hills or post a watchtower.",
    repeatable: true,
    category: "team",
    blockHint: "Watch rotation",
    cta: "Assign watch",
    kind: "proof_of_work",
    dimension: "crew_coordination",
    outcome: "success",
  },
  {
    id: "run_intel_analysis",
    label: "Run intel analysis",
    description: "Forage supplies from meadow plots.",
    repeatable: true,
    category: "support",
    blockHint: "Intelligence briefing",
    cta: "Analyze intel",
    kind: "proof_of_work",
    dimension: "intelligence",
    outcome: "success",
  },
  {
    id: "veteran_intel_sync",
    label: "Veteran intel sync",
    description: "Cross-reference scout feeds with coalition threat database.",
    category: "support",
    blockHint: "Intel sync",
    cta: "Sync intel",
    kind: "proof_of_work",
    dimension: "intelligence",
    outcome: "success",
  },
  {
    id: "misprioritize_sector",
    label: "Misprioritize sector",
    description: "Over-invest in a low-yield sector before noticing drain.",
    category: "edge_cases",
    blockHint: "Strategic error",
    cta: "Overcommit",
    kind: "proof_of_work",
    repeatable: true,
    dimension: "strategic_error",
    outcome: "struggle",
  },
  {
    id: "correct_sector_priority",
    label: "Correct sector priority",
    description: "Rebalance resources after the misallocation.",
    category: "edge_cases",
    blockHint: "Priority recovery",
    cta: "Rebalance",
    kind: "proof_of_work",
    suggestedAfter: ["misprioritize_sector"],
    dimension: "adaptation",
    outcome: "success",
  },
  {
    id: "negotiate_alliance",
    label: "Negotiate alliance",
    description: "Formalize a coalition for shared objective support.",
    category: "integrations",
    blockHint: "Coalition treaty",
    cta: "Sign alliance",
    kind: "proof_of_work",
    dimension: "coalition_building",
    outcome: "success",
  },
  {
    id: "complete_objective_alpha",
    label: "Complete objective Alpha",
    description: "Finish the primary certification mission milestone.",
    category: "activation",
    blockHint: "Mission Alpha",
    cta: "Complete Alpha",
    kind: "proof_of_work",
    dimension: "mission_completion",
    outcome: "success",
  },
  ...createTimeToolActions(),
];

const CATEGORY_ORDER = [
  "onboarding",
  "projects",
  "integrations",
  "team",
  "activation",
  "support",
  "edge_cases",
  "simulation_tools",
] as const;

export const nexusfrontDemo: ProofOfWorkApiDemoDefinition = {
  id: "nexusfront",
  productName: "Haven Rise",
  integrationName: "havenrise-city-agent",
  useCase: USE_CASE,
  tagline: "Gather, build, and grow your city with live Proof-of-Work API scoring",
  saasCategory: "City growth simulation",
  description:
    "A self-contained resource-gathering city builder — survey plots, chop timber, raise districts, and trade in-game while proof-of-work uploads stream automatically to Uncertain Systems.",
  scenarioTitle: "City growth certification",
  scenarioIntro: SCENARIO_INTRO,
  workspaceDescription:
    "Haven Rise city operator certification — verify growth competency through in-game resource gathering and district building with continuous Proof-of-Work API uploads and score-driven coaching overlays.",
  initials: "HR",
  accent: "violet",
  simulatorMode: "game",
  evalDefinition: EVAL_DEFINITION,
  workspacePrompt:
    "Build a certification workspace for Haven Rise operators learning resource gathering, city growth, trade, civic management, and milestone completion.",
  modelDocFilename: "nexusfront-eval-model.md",
  modelDoc: buildModelDoc(
    {
      productName: "Haven Rise",
      integrationName: "havenrise-city-agent",
      evalDefinition: EVAL_DEFINITION,
      modelDocFilename: "nexusfront-eval-model.md",
      useCase: USE_CASE,
      scenarioIntro: SCENARIO_INTRO,
    },
    `| outpost_setup | Commissioning command node and accepting mission brief |
| sector_scouting | Fog-of-war reveal and threat mapping |
| outpost_build | Beacon placement and supply-line extension |
| resource_allocation | Energy grid routing and reserve buffers |
| diplomacy | Trade channels and coalition treaties |
| defense_posture | Perimeter hardening and sentry deployment |
| intelligence | Intel synthesis and briefing quality |
| strategic_error | Misallocated sector investment |
| adaptation | Recovery and priority rebalance |
| coalition_building | Alliance negotiation outcomes |
| mission_completion | Primary objective Alpha completion |
| time_gap | Idle weeks between campaign sessions |`
  ),
  toolName: "nexusfront",
  simulatorToolName: "nexusfront_events",
  schemaVersion: "nexusfront_evidence_v1",
  proofOfWorkGoals: ["frontier_certification", "strategic_competency", "mission_alpha"],
  integrationHints: {
    event_verbs: ["deploy_scout_drone", "establish_beacon", "complete_objective_alpha"],
    goals: ["frontier_certification", "strategic_competency"],
  },
  partnerDescription:
    "Nexus Front partner integration that streams turn-based strategy commands as proof of work to Uncertain Systems.",
  integrationSkillContext: "Nexus Front turn-based strategy game with live proof of work and score overlays",
  categoryMeta: {
    onboarding: {
      label: "Settlement",
      description: "Found the town and survey surrounding plots.",
    },
    integrations: {
      label: "Trade",
      description: "Markets, caravans, and trade pact recovery.",
    },
    projects: {
      label: "Districts",
      description: "Cottages, farms, roads, and granaries.",
    },
    team: {
      label: "Defense",
      description: "City walls and watchtowers.",
    },
    activation: {
      label: "Growth",
      description: "Resource buffers and city milestone completion.",
    },
    support: {
      label: "Civic",
      description: "Census, records, and forage intel.",
    },
    edge_cases: {
      label: "Recovery",
      description: "Overzoning mistakes and growth rebalance.",
    },
    simulation_tools: {
      label: "Season gaps",
      description: "Record idle days between play sessions.",
    },
  },
  categoryOrder: [...CATEGORY_ORDER],
  actions: NEXUSFRONT_ACTIONS,
};