import type { JsonSchema } from "@/lib/xai-client";

export const GENERATED_SIMULATION_SCHEMA: JsonSchema = {
  name: "custom_simulation_spec",
  schema: {
    type: "object",
    additionalProperties: false,
    properties: {
      product_name: { type: "string" },
      tagline: { type: "string" },
      saas_category: { type: "string" },
      use_case: { type: "string" },
      scenario_title: { type: "string" },
      scenario_intro: { type: "string" },
      eval_definition: { type: "string" },
      integration_name: { type: "string" },
      tool_name: { type: "string" },
      competency_rows: { type: "string" },
      categories: {
        type: "array",
        minItems: 3,
        maxItems: 7,
        items: {
          type: "object",
          additionalProperties: false,
          properties: {
            category: {
              type: "string",
              enum: [
                "onboarding",
                "integrations",
                "projects",
                "team",
                "activation",
                "support",
                "edge_cases",
              ],
            },
            label: { type: "string" },
            description: { type: "string" },
            actions: {
              type: "array",
              minItems: 2,
              maxItems: 6,
              items: {
                type: "object",
                additionalProperties: false,
                properties: {
                  id: { type: "string" },
                  label: { type: "string" },
                  description: { type: "string" },
                  block_hint: { type: "string" },
                  cta: { type: "string" },
                  dimension: { type: "string" },
                  outcome: {
                    type: "string",
                    enum: ["success", "partial", "struggle", "failure"],
                  },
                  repeatable: { type: "boolean" },
                },
                required: [
                  "id",
                  "label",
                  "description",
                  "block_hint",
                  "cta",
                  "dimension",
                ],
              },
            },
          },
          required: ["category", "label", "description", "actions"],
        },
      },
    },
    required: [
      "product_name",
      "tagline",
      "saas_category",
      "use_case",
      "scenario_title",
      "scenario_intro",
      "eval_definition",
      "integration_name",
      "tool_name",
      "competency_rows",
      "categories",
    ],
  },
};